using DotLLM.Vulkan.Interop;

namespace DotLLM.Vulkan.Kernels;

/// <summary>
/// Grouped MoE expert projection over PACKED IQ-family expert banks using cooperative matrices (issue #823): the IQ sibling of
/// <see cref="MoeGroupedMatmulLegacyQuantCoopmatKernel"/>. Same row grouping, indirect tile-list and dispatch contract (16-row tiles,
/// 64 output rows per workgroup, wave64), no per-expert scale epilogue. The shaders are generated by
/// <c>native/vulkan/gen_moe_grouped_iq.py</c> from one skeleton; one class serves every <see cref="MoeIqQuant"/>.
/// K must be a multiple of <see cref="MoeIndexedMatmulIqMmvqKernel.GroupSize"/> (256 for IQ3_S / IQ4_XS, 64 for IQ4_NL: one staging round).
/// </summary>
public sealed class MoeGroupedMatmulIqCoopmatKernel : IDisposable
{
    private const int TileN = 16;
    private const int TileM = 64;
    private const int PushConstantBytes = 8 * sizeof(uint);

    private readonly VulkanDevice _device;
    private readonly VulkanModule _module;
    private readonly ComputePipeline _pipeline;
    private readonly nint _descriptorPool;
    private readonly DescriptorSetCache _descriptorCache;
    private readonly VulkanDevice.Buffer[] _codebooks;
    private readonly int _buffersPerSet;
    private bool _disposed;

    /// <summary>The bank format this kernel reads.</summary>
    public MoeIqQuant Quant { get; }

    /// <summary>Bytes per block (super-block for IQ3_S / IQ4_XS).</summary>
    public int BlockBytes { get; }

    /// <summary>Smallest legal K step for the bank: the format's block size, but at least one staging round (64).</summary>
    public int KGroup { get; }

    private MoeGroupedMatmulIqCoopmatKernel(MoeIqQuant quant, VulkanDevice device, VulkanModule module, ComputePipeline pipeline, nint pool,
        int buffersPerSet, VulkanDevice.Buffer[] codebooks)
    {
        Quant = quant;
        var (blockBytes, group) = MoeIqFormats.Describe(quant);
        BlockBytes = blockBytes;
        KGroup = Math.Max(group, 64);
        _device = device;
        _module = module;
        _pipeline = pipeline;
        _descriptorPool = pool;
        _buffersPerSet = buffersPerSet;
        _codebooks = codebooks;
        _descriptorCache = new DescriptorSetCache(device, pool, pipeline, buffersPerSet: buffersPerSet);
    }

    /// <summary>Elements covered by one block of the bank format (the unit the row stride is a multiple of).</summary>
    private int ElementsPerBlock => MoeIqFormats.Describe(Quant).GroupSize;

    /// <summary>The SPIR-V file for <paramref name="quant"/>.</summary>
    public static string SpvName(MoeIqQuant quant) => quant switch
    {
        MoeIqQuant.IQ3_S => "moe_grouped_matmul_iq3_s_coopmat_m64.spv",
        MoeIqQuant.IQ4_XS => "moe_grouped_matmul_iq4_xs_coopmat_m64.spv",
        MoeIqQuant.IQ4_NL => "moe_grouped_matmul_iq4_nl_coopmat_m64.spv",
        MoeIqQuant.IQ2_XXS => "moe_grouped_matmul_iq2_xxs_coopmat_m64.spv",
        MoeIqQuant.IQ2_XS => "moe_grouped_matmul_iq2_xs_coopmat_m64.spv",
        MoeIqQuant.IQ2_S => "moe_grouped_matmul_iq2_s_coopmat_m64.spv",
        MoeIqQuant.IQ3_XXS => "moe_grouped_matmul_iq3_xxs_coopmat_m64.spv",
        MoeIqQuant.Q2_0 => "moe_grouped_matmul_q2_0_coopmat_m64.spv",
        MoeIqQuant.IQ1_M => "moe_grouped_matmul_iq1_m_coopmat_m64.spv",
        _ => throw new ArgumentOutOfRangeException(nameof(quant)),
    };

    /// <summary>
    /// Whether <paramref name="device"/> has cooperative matrices, NATIVE wave64 (the shader bakes 4 x 64-thread subgroups into its
    /// workgroup: on a 32-wide device the surplus subgroups would index shared memory out of bounds and corrupt neighbouring tiles
    /// silently) and the SPIR-V is present.
    /// </summary>
    public static bool IsSupportedOn(VulkanDevice device, string spvDir, MoeIqQuant quant)
        => device.HasCooperativeMatrix && device.SubgroupSize == 64 && File.Exists(Path.Combine(spvDir, SpvName(quant)));

    /// <summary>Creates the kernel for <paramref name="quant"/>; <paramref name="iq3Codebooks"/> supplies the iq3s grid (IQ3_S only; caller keeps ownership).</summary>
    internal static MoeGroupedMatmulIqCoopmatKernel Create(VulkanDevice device, string spvDir, MoeIqQuant quant, Iq3Codebooks? iq3Codebooks = null, Iq2Codebooks? iq2Codebooks = null, Iq1Codebooks? iq1Codebooks = null)
    {
        if (!IsSupportedOn(device, spvDir, quant))
            throw new InvalidOperationException("MoeGroupedMatmulIqCoopmatKernel requires VK_KHR_cooperative_matrix, wave64 and the SPIR-V.");
        var codebooks = MoeIqFormats.Codebooks(quant, iq3Codebooks, iq2Codebooks, iq1Codebooks);
        int buffersPerSet = 4 + codebooks.Length;
        var module = VulkanModule.LoadFromFile(device, Path.Combine(spvDir, SpvName(quant)));
        ComputePipeline pipeline;
        try
        {
            Span<VkDescriptorBinding> bindings = stackalloc VkDescriptorBinding[buffersPerSet];
            for (int i = 0; i < bindings.Length; i++) bindings[i] = new VkDescriptorBinding((uint)i);
            pipeline = module.CreateComputePipeline("main", bindings, PushConstantBytes, requiredSubgroupSize: 0);
        }
        catch
        {
            module.Dispose();
            throw;
        }
        nint pool = KernelSupport.CreateDescriptorPool(device, buffersPerSet: (uint)buffersPerSet);
        return new MoeGroupedMatmulIqCoopmatKernel(quant, device, module, pipeline, pool, buffersPerSet, codebooks);
    }

    internal void InvalidateDescriptorCache() => _descriptorCache.Reset();

    /// <summary>Token rows per workgroup (always 16).</summary>
    public int RowTile => TileN;

    /// <summary>Weight-row tiles per workgroup column (the x extent of the grid): <c>ceil(m / 64)</c>.</summary>
    public int MTiles(int m) => (m + TileM - 1) / TileM;

    /// <summary>Synchronous launch on the legacy 3-D grid; used by unit tests.</summary>
    public void Launch(VulkanDevice.Buffer bank, VulkanDevice.Buffer packedInput, VulkanDevice.Buffer offsets, VulkanDevice.Buffer output,
        int m, int k, int rows, int numExperts, int maxRowsPerExpert = 0)
    {
        using var ctx = _device.CreateSubmitContext();
        ctx.Begin();
        Record(ctx.CommandBuffer, bank, packedInput, offsets, output, m, k, rows, numExperts, maxRowsPerExpert);
        ctx.SubmitAndWait();
    }

    private void Validate(VulkanDevice.Buffer bank, VulkanDevice.Buffer packedInput, VulkanDevice.Buffer output, int m, int k, int rows, int numExperts, out long rowBytes)
    {
        if (m <= 0) throw new ArgumentOutOfRangeException(nameof(m));
        if (rows <= 0) throw new ArgumentOutOfRangeException(nameof(rows));
        if (numExperts <= 0) throw new ArgumentOutOfRangeException(nameof(numExperts));
        if (k <= 0 || (k % KGroup) != 0) throw new ArgumentException($"k must be a positive multiple of {KGroup} for {Quant}, got {k}", nameof(k));
        rowBytes = (long)(k / ElementsPerBlock) * BlockBytes;
        long bankBytes = (long)numExperts * m * rowBytes;
        if (bankBytes > uint.MaxValue) throw new ArgumentException($"bank is {bankBytes} bytes; the shader addresses it with 32-bit byte offsets.", nameof(bank));
        if (bank.Size < bankBytes) throw new ArgumentException("bank buffer too small.", nameof(bank));
        if (packedInput.Size < (long)rows * k * sizeof(float)) throw new ArgumentException("packedInput buffer too small.", nameof(packedInput));
        if (output.Size < (long)rows * m * sizeof(float)) throw new ArgumentException("output buffer too small.", nameof(output));
    }

    /// <summary>Records the grouped matmul on the legacy grid (<paramref name="maxRowsPerExpert"/> bounds the row-tile grid; 0 = <paramref name="rows"/>): <c>output[packedRow, m] = packedInput[packedRow, :] . bank[expert(packedRow), m, :]</c>.</summary>
    public unsafe void Record(nint cmdBuf, VulkanDevice.Buffer bank, VulkanDevice.Buffer packedInput, VulkanDevice.Buffer offsets,
        VulkanDevice.Buffer output, int m, int k, int rows, int numExperts, int maxRowsPerExpert = 0)
    {
        Validate(bank, packedInput, output, m, k, rows, numExperts, out long rowBytes);
        if (offsets.Size < (long)(numExperts + 1) * sizeof(uint)) throw new ArgumentException("offsets buffer too small.", nameof(offsets));
        Bind(cmdBuf, bank, packedInput, offsets, output, m, k, rows, numExperts, rowBytes, tileList: 0);
        int rowTiles = maxRowsPerExpert > 0 ? Math.Min(maxRowsPerExpert, rows) : rows;
        VulkanApi.vkCmdDispatch(cmdBuf, (uint)MTiles(m), (uint)((rowTiles + TileN - 1) / TileN), (uint)numExperts);
    }

    /// <summary>
    /// Indirect variant (see <see cref="MoeGroupedMatmulKQuantCoopmatKernel.RecordIndirect"/>): launches only the real (expert, 16-row tile)
    /// pairs from the list <see cref="MoeBuildTileListKernel"/> wrote after the offsets in <paramref name="offsetsAndTiles"/>.
    /// </summary>
    public unsafe void RecordIndirect(nint cmdBuf, VulkanDevice.Buffer bank, VulkanDevice.Buffer packedInput, VulkanDevice.Buffer offsetsAndTiles,
        VulkanDevice.Buffer output, VulkanDevice.Buffer dispatchArgs, int dispatchArgsOffset, int m, int k, int rows, int numExperts)
    {
        Validate(bank, packedInput, output, m, k, rows, numExperts, out long rowBytes);
        if (dispatchArgs.Size < dispatchArgsOffset + 3 * sizeof(uint)) throw new ArgumentException("dispatchArgs buffer too small.", nameof(dispatchArgs));
        if (offsetsAndTiles.Size < MoeBuildTileListKernel.OffsetsBufferUints(numExperts, rows) * sizeof(uint))
            throw new ArgumentException("offsets/tile-list buffer too small.", nameof(offsetsAndTiles));
        Bind(cmdBuf, bank, packedInput, offsetsAndTiles, output, m, k, rows, numExperts, rowBytes, tileList: (uint)(numExperts + 1));
        VulkanApi.vkCmdDispatchIndirect(cmdBuf, dispatchArgs.Handle, (ulong)dispatchArgsOffset);
    }

    private unsafe void Bind(nint cmdBuf, VulkanDevice.Buffer bank, VulkanDevice.Buffer packedInput, VulkanDevice.Buffer offsets, VulkanDevice.Buffer output,
        int m, int k, int rows, int numExperts, long rowBytes, uint tileList)
    {
        Span<nint> buffers = stackalloc nint[_buffersPerSet];
        buffers[0] = bank.Handle; buffers[1] = packedInput.Handle; buffers[2] = offsets.Handle; buffers[3] = output.Handle;
        for (int i = 0; i < _codebooks.Length; i++) buffers[4 + i] = _codebooks[i].Handle;
        nint descriptorSet = _descriptorCache.GetOrCreate(buffers);
        VulkanApi.vkCmdBindPipeline(cmdBuf, VkPipelineBindPoint.Compute, _pipeline.Pipeline);
        VulkanApi.vkCmdBindDescriptorSets(cmdBuf, VkPipelineBindPoint.Compute, _pipeline.Layout, 0, 1, descriptorSet, 0, 0);
        Span<uint> pc = stackalloc uint[8] { (uint)m, (uint)k, (uint)rows, (uint)numExperts, (uint)(k / 32), (uint)rowBytes, tileList, 0u };
        fixed (uint* pcPtr = pc)
            VulkanApi.vkCmdPushConstants(cmdBuf, _pipeline.Layout, VkShaderStageFlags.Compute, 0, PushConstantBytes, (nint)pcPtr);
    }

    /// <inheritdoc/>
    public void Dispose()
    {
        if (_disposed) return;
        _disposed = true;
        if (_descriptorPool != 0) VulkanApi.vkDestroyDescriptorPool(_device.Handle, _descriptorPool, 0);
        _pipeline.Dispose();
        _module.Dispose();
        // The iq3s grid is owned by Iq3Codebooks.
    }
}
