using System.Text.Json;
using DotLLM.Cpu.Kernels;
using DotLLM.Models.Architectures;
using Xunit;
using Xunit.Abstractions;

namespace DotLLM.Tests.Integration.Engine;

/// <summary>
/// Cross-reference Mamba-3 kernels against the <c>VikramKarLex/mamba3-minimal</c>
/// PyTorch reference. Fixtures generated by
/// <c>tests/DotLLM.Tests.Integration/Fixtures/Mamba3/capture_fixtures.py</c> —
/// regenerate if the kernel contract or reference version changes.
/// </summary>
public class Mamba3ReferenceCompareTests
{
    // Tolerances are deliberately strict. A pure-Python reimplementation of all three
    // kernels (verify_algorithm.py, same fixture) measured max_abs ~ 6e-7, max_rel ~ 5e-7
    // across α/β/γ, B/C qkn, y_scan, ssm_state, prev_Bx. 1e-6 / 1e-5 leaves roughly a 2×
    // margin for C# <-> Python F32 rounding noise. If either tolerance tightens in future
    // kernel revisions, update the Python verifier first and revisit here.
    private const float AbsTol = 1e-6f;
    private const float RelTol = 1e-5f;

    private readonly ITestOutputHelper _output;

    public Mamba3ReferenceCompareTests(ITestOutputHelper output) => _output = output;

    private static string FixturePath() =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "Mamba3", "fixture.json");

    private static string MimoFixturePath() =>
        Path.Combine(AppContext.BaseDirectory, "Fixtures", "Mamba3", "fixture_mimo.json");

    private static Fixture LoadFixture() => LoadFixtureFrom(FixturePath());

    private static Fixture LoadFixtureFrom(string path)
    {
        string fullPath = Path.GetFullPath(path);
        if (!File.Exists(fullPath))
            throw new FileNotFoundException($"Mamba-3 fixture not found at {fullPath}. Run capture_fixtures.py first.");
        using var stream = File.OpenRead(fullPath);
        var f = JsonSerializer.Deserialize<Fixture>(stream, new JsonSerializerOptions
        {
            PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower,
        }) ?? throw new InvalidDataException("Fixture deserialised to null.");
        return f;
    }

    [SkippableFact]
    public void Discretize_MatchesReference()
    {
        Skip.IfNot(File.Exists(Path.GetFullPath(FixturePath())),
            "fixture.json missing — run tests/DotLLM.Tests.Integration/Fixtures/Mamba3/capture_fixtures.py");

        var f = LoadFixture();
        int batch = f.Config["batch"].GetInt32();
        int seqlen = f.Config["seqlen"].GetInt32();
        int nheads = f.Config["nheads"].GetInt32();
        Assert.Equal(1, batch);

        // Inputs (already post-softplus / post-sigmoid per capture script).
        float[] dt = f.Activated["dt"].Data;         // [b, l, h] flat
        float[] lam = f.Activated["lam"].Data;
        float[] a = f.Inputs["A"].Data;              // [h]

        // Expected from reference
        float[] expAlpha = f.Expected["alpha"].Data;
        float[] expBeta = f.Expected["beta"].Data;
        float[] expGamma = f.Expected["gamma"].Data;

        // Run our kernel
        int totalTokens = seqlen;  // batch=1
        float[] alpha = new float[totalTokens * nheads];
        float[] beta = new float[totalTokens * nheads];
        float[] gamma = new float[totalTokens * nheads];

        Mamba3Discretize.Execute(dt, a, lam, alpha, beta, gamma, seqlen, nheads);

        _output.WriteLine($"dt: [{string.Join(", ", dt.Take(4).Select(v => v.ToString("F4")))}, ...]");
        _output.WriteLine($"alpha expected[0..4]: [{string.Join(", ", expAlpha.Take(4).Select(v => v.ToString("F6")))}]");
        _output.WriteLine($"alpha ours[0..4]:     [{string.Join(", ", alpha.Take(4).Select(v => v.ToString("F6")))}]");

        AssertCloseElementwise("alpha", expAlpha, alpha);
        AssertCloseElementwise("beta", expBeta, beta);
        AssertCloseElementwise("gamma", expGamma, gamma);
    }

    [SkippableFact]
    public void QkNorm_MatchesReference()
    {
        Skip.IfNot(File.Exists(Path.GetFullPath(FixturePath())),
            "fixture.json missing — run capture_fixtures.py");

        var f = LoadFixture();
        int seqlen = f.Config["seqlen"].GetInt32();
        int dState = f.Config["d_state"].GetInt32();
        const float eps = 1e-5f;

        // Reference QK-norm uses a single RMSNorm(bc_dim) layer before group split;
        // in SISO bc_dim == d_state and there is no group dim, so our [T, nGroup=1, dState] layout matches.
        int nGroup = 1;
        float[] bIn = (float[])f.Inputs["B_raw"].Data.Clone();
        float[] cIn = (float[])f.Inputs["C_raw"].Data.Clone();
        float[] bWeight = f.Inputs["B_norm_weight"].Data;
        float[] cWeight = f.Inputs["C_norm_weight"].Data;

        Mamba3QkNorm.Execute(bIn, bWeight, eps, seqlen, nGroup, dState);
        Mamba3QkNorm.Execute(cIn, cWeight, eps, seqlen, nGroup, dState);

        AssertCloseElementwise("B_qkn", f.Expected["B_qkn"].Data, bIn);
        AssertCloseElementwise("C_qkn", f.Expected["C_qkn"].Data, cIn);
    }

    [SkippableFact]
    public void SelectiveScan_MatchesReference()
    {
        Skip.IfNot(File.Exists(Path.GetFullPath(FixturePath())),
            "fixture.json missing — run capture_fixtures.py");

        var f = LoadFixture();
        int seqlen = f.Config["seqlen"].GetInt32();
        int nHead = f.Config["nheads"].GetInt32();
        int headDim = f.Config["headdim"].GetInt32();
        int dState = f.Config["d_state"].GetInt32();
        int nGroup = nHead;   // post-BC-bias-broadcast, B/C are per-head
        int dInner = nHead * headDim;

        // Inputs to the scan: pre-computed α/β/γ and post-RoPE B/C from the fixture.
        float[] alpha = f.Expected["alpha"].Data;
        float[] beta = f.Expected["beta"].Data;
        float[] gamma = f.Expected["gamma"].Data;
        float[] bRoped = f.Expected["B_roped"].Data;   // (b=1, l, nHead, dState) flat
        float[] cRoped = f.Expected["C_roped"].Data;

        // Reference flattens x as (b, l, h, p); our scan expects [T, dInner=h*p] row-major.
        // Since x_heads in the fixture is stored (1, seqlen, nHead, headDim) row-major, a flat
        // reinterpret is exactly [seqlen, nHead*headDim] = [seqlen, dInner]. ✓
        float[] x = f.Inputs["x"].Data;

        float[] state = new float[nHead * headDim * dState];
        float[] prevBx = new float[nHead * headDim * dState];
        float[] y = new float[seqlen * dInner];

        Mamba3SelectiveScan.Execute(state, prevBx, x, alpha, beta, gamma, bRoped, cRoped, y,
            nHead, headDim, dState, nGroup, seqlen);

        // Reference y_scan has shape (b=1, l, h, p) row-major — same flat layout as [seqlen, dInner].
        AssertCloseElementwise("y_scan", f.Expected["y_scan"].Data, y);

        // Recurrent state sanity: last_Bx should equal our prev_Bx after the scan.
        AssertCloseElementwise("prev_Bx == last_Bx", f.Expected["last_Bx"].Data, prevBx);

        // ssm_state shape in reference is (b=1, h, p, n) — our state is [h, p, n]; same flat layout.
        AssertCloseElementwise("ssm_state", f.Expected["ssm_state"].Data, state);
    }

    [SkippableFact]
    public void Block_MatchesReference()
    {
        Skip.IfNot(File.Exists(Path.GetFullPath(FixturePath())),
            "fixture.json missing — run capture_fixtures.py");

        var f = LoadFixture();
        int seqlen = f.Config["seqlen"].GetInt32();
        int dModel = f.Config["d_model"].GetInt32();
        int dInner = f.Config["d_inner"].GetInt32();
        int nHead = f.Config["nheads"].GetInt32();
        int headDim = f.Config["headdim"].GetInt32();
        int dState = f.Config["d_state"].GetInt32();

        float[] u = f.Inputs["u"].Data;
        float[] inProj = f.Inputs["in_proj_weight"].Data;
        float[] outProj = f.Inputs["out_proj_weight"].Data;
        float[] a = f.Inputs["A"].Data;
        float[] dtBias = f.Inputs["dt_bias"].Data;
        float[] bNormW = f.Inputs["B_norm_weight"].Data;
        float[] cNormW = f.Inputs["C_norm_weight"].Data;
        float[] bBias = f.Inputs["B_bias"].Data;
        float[] cBias = f.Inputs["C_bias"].Data;
        float[] dVec = f.Inputs["D"].Data;

        float[] state = new float[nHead * headDim * dState];
        float[] prevBx = new float[nHead * headDim * dState];
        float[] y = new float[seqlen * dModel];

        Mamba3Block.Forward(
            u, inProj, outProj,
            a, dtBias, bNormW, cNormW, bBias, cBias, dVec,
            y, state, prevBx,
            seqlen, dModel, dInner, nHead, headDim, dState);

        AssertCloseElementwise("y_final", f.Expected["y_final"].Data, y);

        // Also confirm final SSM state and prev_Bx match — confirms the block
        // kept the recurrent caches correctly through the whole pipeline.
        AssertCloseElementwise("ssm_state (after block)", f.Expected["ssm_state"].Data, state);
        AssertCloseElementwise("prev_Bx (after block)", f.Expected["last_Bx"].Data, prevBx);
    }

    [SkippableFact]
    public void Block_MIMO_MatchesReference()
    {
        Skip.IfNot(File.Exists(Path.GetFullPath(MimoFixturePath())),
            "fixture_mimo.json missing — run capture_fixtures.py");

        var f = LoadFixtureFrom(MimoFixturePath());
        int seqlen = f.Config["seqlen"].GetInt32();
        int dModel = f.Config["d_model"].GetInt32();
        int dInner = f.Config["d_inner"].GetInt32();
        int nHead = f.Config["nheads"].GetInt32();
        int headDim = f.Config["headdim"].GetInt32();
        int dState = f.Config["d_state"].GetInt32();
        int R = f.Config["mimo_rank"].GetInt32();
        Assert.True(f.Config["use_mimo"].GetBoolean(), "Expected use_mimo=true fixture");
        Assert.Equal(2, R);

        float[] u = f.Inputs["u"].Data;
        float[] inProj = f.Inputs["in_proj_weight"].Data;
        float[] outProj = f.Inputs["out_proj_weight"].Data;
        float[] a = f.Inputs["A"].Data;
        float[] dtBias = f.Inputs["dt_bias"].Data;
        float[] bNormW = f.Inputs["B_norm_weight"].Data;
        float[] cNormW = f.Inputs["C_norm_weight"].Data;
        float[] bBias = f.Inputs["B_bias"].Data;
        float[] cBias = f.Inputs["C_bias"].Data;
        float[] dVec = f.Inputs["D"].Data;
        float[] mimoXProj = f.Inputs["mimo_x_proj"].Data;
        float[] mimoZProj = f.Inputs["mimo_z_proj"].Data;
        float[] mimoDown = f.Inputs["mimo_down"].Data;

        float[] state = new float[nHead * headDim * dState];
        float[] prevBx = new float[nHead * headDim * dState];
        float[] y = new float[seqlen * dModel];

        Mamba3Block.ForwardMimo(
            u, inProj, outProj,
            a, dtBias, bNormW, cNormW, bBias, cBias, dVec,
            mimoXProj, mimoZProj, mimoDown,
            y, state, prevBx,
            seqlen, dModel, dInner, nHead, headDim, dState, R);

        _output.WriteLine($"MIMO y_final max_abs/max_rel: {DriftStats("y_final", f.Expected["y_final"].Data, y)}");
        _output.WriteLine($"MIMO ssm_state max_abs/max_rel: {DriftStats("ssm_state", f.Expected["ssm_state"].Data, state)}");
        _output.WriteLine($"MIMO prev_Bx max_abs/max_rel: {DriftStats("prev_Bx", f.Expected["last_Bx"].Data, prevBx)}");

        AssertCloseElementwise("y_final (MIMO)", f.Expected["y_final"].Data, y);

        // Recurrent caches — shape identical to SISO because rank is contracted
        // in the MIMO scan's B·x term.
        AssertCloseElementwise("ssm_state (MIMO, after block)", f.Expected["ssm_state"].Data, state);
        AssertCloseElementwise("prev_Bx (MIMO, after block)", f.Expected["last_Bx"].Data, prevBx);
    }

    private static string DriftStats(string _, float[] expected, float[] actual)
    {
        float maxAbs = 0f, maxRel = 0f;
        for (int i = 0; i < expected.Length; i++)
        {
            float e = expected[i];
            float aa = actual[i];
            float d = MathF.Abs(e - aa);
            float r = d / (MathF.Abs(e) + 1e-12f);
            if (d > maxAbs) maxAbs = d;
            if (r > maxRel) maxRel = r;
        }
        return $"max_abs={maxAbs:E3} max_rel={maxRel:E3}";
    }

    private static void AssertCloseElementwise(string label, float[] expected, float[] actual)
    {
        Assert.Equal(expected.Length, actual.Length);
        for (int i = 0; i < expected.Length; i++)
        {
            float e = expected[i];
            float a = actual[i];
            float absDiff = MathF.Abs(e - a);
            float relDiff = absDiff / (MathF.Abs(e) + 1e-12f);
            if (absDiff > AbsTol && relDiff > RelTol)
            {
                Assert.Fail($"{label}[{i}]: expected={e:F8} actual={a:F8} absDiff={absDiff:E3} relDiff={relDiff:E3} "
                            + $"(tolerance abs={AbsTol:E0} rel={RelTol:E0})");
            }
        }
    }

    // ── Fixture DTOs ──────────────────────────────────────────────────────────

    private sealed class Fixture
    {
        public Dictionary<string, JsonElement> Config { get; set; } = default!;
        public Dictionary<string, Tensor> Inputs { get; set; } = default!;
        public Dictionary<string, Tensor> Activated { get; set; } = default!;
        public Dictionary<string, Tensor> Expected { get; set; } = default!;
    }

    private sealed class Tensor
    {
        public int[] Shape { get; set; } = [];
        public float[] Data { get; set; } = [];
    }
}
