using DotLLM.Core.Configuration;
using DotLLM.Core.Models;
using DotLLM.Core.Tensors;
using DotLLM.Models.Architectures;
using DotLLM.Models.SafeTensors;
using DotLLM.Tests.Unit.Models.SafeTensors;
using Xunit;
using Xunit.Abstractions;

namespace DotLLM.Tests.Unit.Models.Architectures;

/// <summary>
/// End-to-end MIMO path coverage for <see cref="Mamba3TransformerModel"/>
/// against a synthetic Mamba-3 MIMO checkpoint built in-process. No public
/// MIMO Mamba-3 checkpoint exists, so these tests use a seeded-cosine
/// fixture generated by
/// <see cref="SafetensorsFixtureBuilder.WriteTinyMamba3MimoFixture(string, int, int, int, int, int, int, int, int, int, bool, int)"/>.
/// </summary>
/// <remarks>
/// <para>
/// <b>What these tests assert.</b>
/// </para>
/// <list type="bullet">
///   <item><description>
///     <see cref="Mamba3WeightLoader"/> populates the MIMO-only per-rank
///     tensors (<c>mimo_x</c>, <c>mimo_z</c>, <c>mimo_o</c>) with the
///     expected <c>[H, R, P]</c> shape and carries <c>B_bias</c> /
///     <c>C_bias</c> at <c>[H, R, N]</c> (not <c>[H, 1, N]</c> as SISO does).
///   </description></item>
///   <item><description>
///     The model's one-shot <see cref="Mamba3TransformerModel.Forward(ReadOnlySpan{int}, ReadOnlySpan{int}, int)"/>
///     no longer throws <see cref="NotSupportedException"/> on a MIMO config
///     (P0.3 — previously a hard block); it returns a finite logits tensor.
///   </description></item>
///   <item><description>
///     A prefill + per-token decode over a persistent <see cref="Mamba3State"/>
///     advances the MIMO-specific <c>[R, H, N]</c> <c>k_state</c> and
///     <c>[H, P]</c> <c>v_state</c> across calls, mirroring the SISO
///     streaming-decode contract.
///   </description></item>
/// </list>
/// <para>
/// The fixture dims are intentionally tiny (2 layers, hidden=16, H=2, R=2,
/// N=8) — the forward is microseconds, every per-layer tensor fits in
/// &lt; 2 KB, and the whole fixture file is &lt; 20 KB.
/// </para>
/// </remarks>
public sealed class Mamba3TransformerModelMimoTests : IDisposable
{
    // Tiny MIMO shape tuple. Constraints:
    //   d_inner = n_head * head_dim                (enforced by Mamba3Block.ValidateCommon)
    //   2 * num_rope_angles <= state_size
    //   num_rope_angles = int(state_size * rope_fraction) / 2  (Mamba3Config)
    //   bc_per_token = state_size * num_bc_heads * mimo_rank   (MIMO: R-expanded)
    //   d_in_proj = 2*d_inner + 2*bc_per_token + 3*n_head + num_rope_angles
    private const int HiddenSize = 16;
    private const int VocabSize = 16;
    private const int NumLayers = 2;
    private const int NumHeads = 2;
    private const int HeadDim = 8;
    private const int DInner = NumHeads * HeadDim;              // 16
    private const int Expand = 1;                               // hidden * 1 == d_inner
    private const int StateSize = 8;
    private const int NumBcHeads = 1;
    private const int MimoRank = 2;
    private const float RopeFraction = 0.5f;
    private const int NumRopeAngles = 2;                        // int(8 * 0.5) / 2
    private const int BcPerToken = StateSize * NumBcHeads * MimoRank; // 16
    private const int DInProj = 2 * DInner + 2 * BcPerToken + 3 * NumHeads + NumRopeAngles; // 72

    private readonly string _scratch;
    private readonly ITestOutputHelper _output;

    public Mamba3TransformerModelMimoTests(ITestOutputHelper output)
    {
        _output = output;
        _scratch = Path.Combine(Path.GetTempPath(), $"dotllm-m3mimo-{Guid.NewGuid():N}");
        Directory.CreateDirectory(_scratch);
    }

    public void Dispose()
    {
        try { Directory.Delete(_scratch, recursive: true); } catch { /* best-effort */ }
    }

    private string Scratch(string name) => Path.Combine(_scratch, name);

    private static ModelConfig BuildConfig()
    {
        var m3 = new Mamba3Config
        {
            StateSize = StateSize,
            NumHeads = NumHeads,
            HeadDim = HeadDim,
            Expand = Expand,
            NumGroups = NumBcHeads,
            ChunkSize = 2,
            IsMimo = true,
            MimoRank = MimoRank,
            AFloor = 1e-4f,
            DtInitFloor = 1e-4f,
            DtMin = 1e-3f,
            DtMax = 0.1f,
            UseL2Warp = false,
            RopeFraction = RopeFraction,
            IsOutProjNorm = false,
            RescalePrenormResidual = true,
            ResidualInFp32 = true,
        };
        return new ModelConfig
        {
            Architecture = Architecture.Mamba3,
            VocabSize = VocabSize,
            HiddenSize = HiddenSize,
            IntermediateSize = 0,
            NumLayers = NumLayers,
            NumAttentionHeads = NumHeads,
            NumKvHeads = NumHeads,
            HeadDim = HeadDim,
            MaxSequenceLength = 32,
            AttentionType = AttentionType.GQA,
            PositionEncodingType = PositionEncodingType.None,
            RoPEConfig = null,
            ActivationFunction = ActivationFunction.SiLU,
            NormType = NormType.RMSNorm,
            NormEpsilon = 1e-5f,
            TiedEmbeddings = false,
            SlidingWindowSize = null,
            MlaConfig = null,
            HybridLayout = null,
            SsmConfig = null,
            Mamba3Config = m3,
            ChatTemplate = null,
        };
    }

    // ────────────────────────────────────────────────────────────────────
    // Loader — MIMO-specific tensor set and shapes
    // ────────────────────────────────────────────────────────────────────

    [Fact]
    public void Loader_MimoFixture_PopulatesMimoXZO_WithRankExpandedBias()
    {
        // Verify the canonical MIMO tensor layout the P0.3 loader extension
        // promises:
        //   B_bias, C_bias  → [H, R, N]  (not [H, 1, N] as SISO uses)
        //   mimo_x, mimo_z, mimo_o → [H, R, P]  (populated; non-empty handles)
        string path = Scratch("mimo-tiny.safetensors");
        SafetensorsFixtureBuilder.WriteTinyMamba3MimoFixture(
            path, NumLayers, HiddenSize, VocabSize, NumHeads, HeadDim,
            StateSize, DInProj, DInner, MimoRank);

        using var sf = SafetensorsFile.Open(path);
        using var weights = Mamba3WeightLoader.Load(BuildConfig(), sf);

        Assert.False(weights.Report.HasMissingRequired);
        Assert.Equal(NumLayers, weights.Layers.Length);

        foreach (var layer in weights.Layers)
        {
            Assert.True(layer.BBias.IsPopulated);
            Assert.True(layer.CBias.IsPopulated);
            Assert.True(layer.MimoX.IsPopulated);
            Assert.True(layer.MimoZ.IsPopulated);
            Assert.True(layer.MimoO.IsPopulated);

            // Bias shape: [H, R, N] — the rank axis is populated (vs SISO's
            // singleton).
            Assert.Equal(new[] { NumHeads, MimoRank, StateSize }, layer.BBias.Shape);
            Assert.Equal(new[] { NumHeads, MimoRank, StateSize }, layer.CBias.Shape);

            // MIMO per-rank weights: [H, R, P] — matches canonical init.
            Assert.Equal(new[] { NumHeads, MimoRank, HeadDim }, layer.MimoX.Shape);
            Assert.Equal(new[] { NumHeads, MimoRank, HeadDim }, layer.MimoZ.Shape);
            Assert.Equal(new[] { NumHeads, MimoRank, HeadDim }, layer.MimoO.Shape);
        }

        // Loaded-count accounting: 3 globals + (9 SISO tensors + 3 MIMO tensors) per layer.
        Assert.Equal(3 + NumLayers * Mamba3TensorMapping.PerLayerMimoTensorCount, weights.Report.LoadedCount);
    }

    [Fact]
    public void Loader_MissingMimoX_IsFlaggedAsMissingRequired()
    {
        // Omit mimo_x on layer 0 of a MIMO checkpoint. The loader must surface
        // the Missing diagnostic (canonical MIMO scan is correctness-sensitive
        // to all three per-rank weights — canonical_mimo_scan treats each as
        // a required parameter even though our current kernel folds mimo_x
        // into the K.sum update).
        string path = Scratch("mimo-missing-x.safetensors");
        var b = new SafetensorsFixtureBuilder();
        b.AddFloat32(Mamba3TensorMapping.TokenEmbedding, [VocabSize, HiddenSize]);
        b.AddFloat32(Mamba3TensorMapping.FinalNorm, [HiddenSize]);
        b.AddFloat32(Mamba3TensorMapping.LmHead, [VocabSize, HiddenSize]);
        for (int i = 0; i < NumLayers; i++)
        {
            b.AddFloat32(Mamba3TensorMapping.LayerNorm(i), [HiddenSize]);
            b.AddFloat32(Mamba3TensorMapping.InProj(i), [DInProj, HiddenSize]);
            b.AddFloat32(Mamba3TensorMapping.OutProj(i), [HiddenSize, DInner]);
            b.AddFloat32(Mamba3TensorMapping.BNorm(i), [StateSize]);
            b.AddFloat32(Mamba3TensorMapping.CNorm(i), [StateSize]);
            b.AddFloat32(Mamba3TensorMapping.BBias(i), [NumHeads, MimoRank, StateSize]);
            b.AddFloat32(Mamba3TensorMapping.CBias(i), [NumHeads, MimoRank, StateSize]);
            b.AddFloat32(Mamba3TensorMapping.D(i), [NumHeads]);
            b.AddFloat32(Mamba3TensorMapping.DtBias(i), [NumHeads]);
            // mimo_x only for layer 1; omit from layer 0.
            if (i == 1)
                b.AddFloat32(Mamba3TensorMapping.MimoX(i), [NumHeads, MimoRank, HeadDim]);
            b.AddFloat32(Mamba3TensorMapping.MimoZ(i), [NumHeads, MimoRank, HeadDim]);
            b.AddFloat32(Mamba3TensorMapping.MimoO(i), [NumHeads, MimoRank, HeadDim]);
        }
        b.WriteTo(path);

        using var sf = SafetensorsFile.Open(path);
        using var weights = Mamba3WeightLoader.Load(BuildConfig(), sf);

        Assert.True(weights.Report.HasMissingRequired);
        Assert.Contains(weights.Report.Problems,
            p => p.TensorName == Mamba3TensorMapping.MimoX(0) &&
                 p.Kind == Mamba3TensorIssueKind.Missing);
    }

    // ────────────────────────────────────────────────────────────────────
    // End-to-end forward — MIMO no longer throws, produces finite logits
    // ────────────────────────────────────────────────────────────────────

    [Fact]
    public void Forward_MimoConfig_DoesNotThrow_ProducesFiniteLogits()
    {
        // Regression guard for the removed NotSupportedException branch in
        // Mamba3TransformerModel.ForwardCore. Before P0.3 a MIMO config
        // was a hard block; after P0.3 the forward dispatches to
        // Mamba3Block.ForwardMimo and returns finite logits.
        string path = Scratch("mimo-forward.safetensors");
        SafetensorsFixtureBuilder.WriteTinyMamba3MimoFixture(
            path, NumLayers, HiddenSize, VocabSize, NumHeads, HeadDim,
            StateSize, DInProj, DInner, MimoRank);

        using var sf = SafetensorsFile.Open(path);
        ModelConfig cfg = BuildConfig();
        using var model = Mamba3TransformerModel.LoadFromSafetensors(sf, cfg);

        int[] tokens = [0, 1, 2];
        int[] positions = [0, 1, 2];
        using ITensor logits = model.Forward(tokens, positions, -1);

        Assert.Equal(2, logits.Shape.Rank);
        Assert.Equal(tokens.Length, logits.Shape[0]);
        Assert.Equal(VocabSize, logits.Shape[1]);

        float[] values = TensorToArray(logits);
        int finiteCount = 0;
        float minV = float.PositiveInfinity, maxV = float.NegativeInfinity;
        foreach (float v in values)
        {
            Assert.True(!float.IsNaN(v), $"NaN logit in MIMO forward output (of {values.Length}).");
            Assert.True(!float.IsInfinity(v), $"Infinite logit in MIMO forward output.");
            if (v < minV) minV = v;
            if (v > maxV) maxV = v;
            finiteCount++;
        }
        Assert.Equal(values.Length, finiteCount);
        _output.WriteLine($"MIMO prefill logits: min={minV:F6} max={maxV:F6} count={values.Length}");

        // The tiny fixture's weights are not pathological, so logits should
        // have non-zero spread across the vocab — otherwise the forward might
        // be silently zeroing somewhere.
        Assert.True(maxV - minV > 1e-6f,
            $"MIMO logits have trivial spread ({maxV - minV:E3}) — forward may be producing a constant.");
    }

    [Fact]
    public void Forward_MimoConfig_GeneratesSeveralTokens_AcrossPersistentState()
    {
        // Prefill a short prompt, then iteratively argmax + feed one token
        // back through the MIMO block with the state threaded. Asserts the
        // state evolves (k_state / v_state move off zero after the first
        // call) and every generated token index is in-range.
        string path = Scratch("mimo-generate.safetensors");
        SafetensorsFixtureBuilder.WriteTinyMamba3MimoFixture(
            path, NumLayers, HiddenSize, VocabSize, NumHeads, HeadDim,
            StateSize, DInProj, DInner, MimoRank);

        using var sf = SafetensorsFile.Open(path);
        ModelConfig cfg = BuildConfig();
        using var model = Mamba3TransformerModel.LoadFromSafetensors(sf, cfg);

        int[] prompt = [0, 1];
        int[] promptPositions = [0, 1];
        using var state = new Mamba3State(cfg);

        // Prefill.
        int nextToken;
        using (ITensor prefill = model.Forward(prompt, promptPositions, -1, state))
        {
            float[] lastRow = LastRow(prefill);
            nextToken = ArgMax(lastRow);
        }

        // K/V state must have advanced off zero on every layer after prefill.
        for (int layer = 0; layer < cfg.NumLayers; layer++)
        {
            Assert.True(AnyNonZero(state.KState(layer)),
                $"MIMO k_state at layer {layer} is still all-zero after MIMO prefill.");
            Assert.True(AnyNonZero(state.VState(layer)),
                $"MIMO v_state at layer {layer} is still all-zero after MIMO prefill.");
        }

        // Capture k_state / v_state snapshots to prove they evolve between calls.
        float[][] kBefore = new float[cfg.NumLayers][];
        float[][] vBefore = new float[cfg.NumLayers][];
        for (int layer = 0; layer < cfg.NumLayers; layer++)
        {
            kBefore[layer] = state.KState(layer).ToArray();
            vBefore[layer] = state.VState(layer).ToArray();
        }

        // Decode a few tokens — feed each argmax back as the next input.
        var generated = new List<int> { nextToken };
        int basePos = prompt.Length;
        const int GenSteps = 4;
        for (int step = 0; step < GenSteps; step++)
        {
            int[] tokIn = [nextToken];
            int[] posIn = [basePos + step];
            using ITensor logits = model.Forward(tokIn, posIn, -1, state);
            float[] row = LastRow(logits);
            nextToken = ArgMax(row);
            generated.Add(nextToken);
        }

        _output.WriteLine($"MIMO generated tokens: [{string.Join(", ", generated)}]");

        // Every generated token must be a valid vocab index.
        foreach (int t in generated)
        {
            Assert.InRange(t, 0, VocabSize - 1);
        }

        // State advanced at least once on at least one layer (some layers may
        // have coincidentally stable k/v depending on the cosine fixture, but
        // with two layers and 4+1 decode steps at least one should move).
        bool anyAdvance = false;
        for (int layer = 0; layer < cfg.NumLayers; layer++)
        {
            if (!ArraysEqual(kBefore[layer], state.KState(layer).ToArray())) { anyAdvance = true; break; }
            if (!ArraysEqual(vBefore[layer], state.VState(layer).ToArray())) { anyAdvance = true; break; }
        }
        Assert.True(anyAdvance,
            "MIMO decode state did not advance across calls — streaming state may not be threaded.");
    }

    [Fact]
    public void MimoState_HasRankExpandedKState_ForMimoConfig()
    {
        // Regression guard: Mamba3State's k_state must be sized [R, H, N] for
        // is_mimo=true (matches canonical mamba3.py:434-445). Already covered
        // by Mamba3TransformerModelDecodeTests.Mamba3State_MimoKStateIsRankExpanded
        // for the raw state, but here we bind the assertion to the same tiny
        // MIMO ModelConfig the forward path uses so a future refactor that
        // breaks the rank contract on one side shows up on both.
        ModelConfig cfg = BuildConfig();
        using var state = new Mamba3State(cfg);
        Assert.Equal(MimoRank * NumHeads * StateSize, state.KStateElementsPerLayer);
        Assert.Equal(NumHeads * HeadDim, state.VStateElementsPerLayer);
    }

    // ────────────────────────────────────────────────────────────────────
    // Helpers
    // ────────────────────────────────────────────────────────────────────

    private static unsafe float[] TensorToArray(ITensor t)
    {
        int total = 1;
        for (int i = 0; i < t.Shape.Rank; i++) total *= t.Shape[i];
        float[] result = new float[total];
        new ReadOnlySpan<float>((void*)t.DataPointer, total).CopyTo(result);
        return result;
    }

    private static unsafe float[] LastRow(ITensor t)
    {
        // Shape [T, V] — return the last V values.
        int seqLen = t.Shape[0];
        int vocab = t.Shape[1];
        float[] row = new float[vocab];
        var all = new ReadOnlySpan<float>((void*)t.DataPointer, seqLen * vocab);
        all.Slice((seqLen - 1) * vocab, vocab).CopyTo(row);
        return row;
    }

    private static int ArgMax(float[] values)
    {
        int best = 0;
        float bestVal = values[0];
        for (int i = 1; i < values.Length; i++)
        {
            if (values[i] > bestVal) { bestVal = values[i]; best = i; }
        }
        return best;
    }

    private static bool AnyNonZero(ReadOnlySpan<float> span)
    {
        for (int i = 0; i < span.Length; i++)
            if (MathF.Abs(span[i]) > 1e-12f) return true;
        return false;
    }

    private static bool ArraysEqual(float[] a, float[] b)
    {
        if (a.Length != b.Length) return false;
        for (int i = 0; i < a.Length; i++)
            if (a[i] != b[i]) return false;
        return true;
    }
}
