using System.Runtime.InteropServices;
using System.Runtime.Intrinsics.X86;
using System.Text.Json;
using DotLLM.Cpu.Kernels.Experimental;
using Xunit;

namespace DotLLM.Tests.Unit.Cpu.Kernels;

/// <summary>
/// Issue #860: the clean-room QAT trainer (tools/littlebit-qat) exports int32-packed sign factors. This proves the
/// spike's byte layout (#832) is identical to that checkpoint layout and that the spike's kernels reproduce the
/// trainer's float64 reference on a layer whose r (40) and d_in (100) are not multiples of 32.
/// Fixture: <c>LittleBitData/littlebit_packed_fixture.json</c>, generated by <c>tools/littlebit-qat/smoke_test.py</c>.
/// </summary>
public sealed unsafe class LittleBitPackedFormatTests
{
    private static JsonElement Load(out JsonDocument doc)
    {
        string path = Path.Combine(AppContext.BaseDirectory, "Cpu", "Kernels", "LittleBitData", "littlebit_packed_fixture.json");
        doc = JsonDocument.Parse(File.ReadAllText(path));
        return doc.RootElement;
    }

    private static int[][] Words(JsonElement e) =>
        e.EnumerateArray().Select(r => r.EnumerateArray().Select(w => w.GetInt32()).ToArray()).ToArray();

    private static float[] F(JsonElement e) => e.EnumerateArray().Select(x => x.GetSingle()).ToArray();

    private static int Bit(int[] row, int c) => (row[c >> 5] >> (c & 31)) & 1;   // LSB-first; 1 == -1

    private static LittleBitLayer Build(JsonElement root, out int[][][] uWords, out int[][][] vWords)
    {
        int dOut = root.GetProperty("d_out").GetInt32(), dIn = root.GetProperty("d_in").GetInt32(), r = root.GetProperty("r").GetInt32();
        var paths = new List<LittleBitPath>();
        var uw = new List<int[][]>(); var vw = new List<int[][]>();
        foreach (var p in root.GetProperty("paths").EnumerateArray())
        {
            int[][] U = Words(p.GetProperty("U_packed")), V = Words(p.GetProperty("V_packed"));   // U (d_out, ceil(r/32)), V (r, ceil(d_in/32))
            uw.Add(U); vw.Add(V);
            var us = new sbyte[dOut * r]; var vs = new sbyte[dIn * r];
            for (int o = 0; o < dOut; o++) for (int j = 0; j < r; j++) us[o * r + j] = (sbyte)(Bit(U[o], j) == 1 ? -1 : 1);
            for (int i = 0; i < dIn; i++) for (int j = 0; j < r; j++) vs[i * r + j] = (sbyte)(Bit(V[j], i) == 1 ? -1 : 1);   // spike Vs is [d_in x r]
            Half[] H(string n) => F(p.GetProperty(n)).Select(x => (Half)x).ToArray();
            // spike holds ONE latent vector l = bf16(v1*u2); scales are bf16 values inside fp16's normal range, so exact.
            paths.Add(LittleBitPath.FromSigns(dOut, dIn, r, us, vs, H("u1"), H("v2"), H("l")));
        }
        uWords = uw.ToArray(); vWords = vw.ToArray();
        return new LittleBitLayer(paths.ToArray());
    }

    [Fact]
    public void SpikePackedBytes_AreIdenticalToCheckpointInt32Words()
    {
        var root = Load(out var doc);
        using (doc)
        {
            using var layer = Build(root, out var uw, out var vw);
            for (int pi = 0; pi < layer.Paths.Length; pi++)
            {
                var p = layer.Paths[pi];
                Assert.Equal(uw[pi][0].Length * 4, p.RPad / 8);       // ceil(r/32) words == RPad/8 bytes
                Assert.Equal(vw[pi][0].Length * 4, p.DInPad / 8);
                for (int o = 0; o < p.DOut; o++)
                    Assert.True(MemoryMarshal.AsBytes<int>(uw[pi][o]).SequenceEqual(new ReadOnlySpan<byte>(p.UBits + (long)o * (p.RPad / 8), p.RPad / 8)), $"U row {o}");
                for (int j = 0; j < p.R; j++)
                    Assert.True(MemoryMarshal.AsBytes<int>(vw[pi][j]).SequenceEqual(new ReadOnlySpan<byte>(p.VBits + (long)j * (p.DInPad / 8), p.DInPad / 8)), $"V row {j}");
            }
        }
    }

    [Fact]
    public void Fixture_MatchesTrainerFloat64Reference_AndBf16Pipeline()
    {
        var root = Load(out var doc);
        using (doc)
        {
            using var layer = Build(root, out _, out _);
            float[] x = F(root.GetProperty("x"));
            double[] y = root.GetProperty("y_ref64").EnumerateArray().Select(e => e.GetDouble()).ToArray();
            float[] ybf = F(root.GetProperty("y_bf16"));
            var scalar = LittleBitReference.Gemv(layer, x);
            double scale = y.Max(Math.Abs);
            for (int i = 0; i < y.Length; i++)
            {
                Assert.Equal(y[i], scalar[i], 1e-9 * (1 + Math.Abs(y[i])));
                Assert.True(Math.Abs(y[i] - ybf[i]) / scale < 0.05);   // bf16 pipeline drift, loose by design
            }
            if (!Avx2.IsSupported) return;
            var (dIn, r) = layer.ScratchDims;
            using var sc = new LittleBitScratch(dIn, r);
            var got = new float[layer.DOut];
            fixed (float* xp = x, yp = got) layer.Gemv(xp, yp, sc, null, LittleBitKernel.Avx2Float);
            for (int i = 0; i < y.Length; i++) Assert.True(Math.Abs(y[i] - got[i]) / scale < 1e-5, $"row {i}");
        }
    }
}
