#!/usr/bin/env python3
"""Generates variants of the blocked 128x128x4 coopmat GEMM shaders from their base files.

1. Split-K twins (*_splitk.comp): for grids with fewer tiles than compute units (small m at n = 128: ffn-down and the
   attention/GDN output projections launch 20-32 workgroups on a 40-CU part), gl_WorkGroupID.z selects a K slice and a private
   C slab; splitk_reduce_f32.comp sums the slabs. The twin differs from its base shader only by one extra push constant
   (chunksPerSplit) and two defines, so the quant-specific A-staging code is reused verbatim.

2. F16-activation variants (*_bh.comp and *_bh_splitk.comp): B (the activations) is read as f16vec4[] instead of vec4[], i.e.
   half the activation traffic. The template already stages B into LDS as F16, so feeding it activations that the producer
   rounded to F16 once is bit-identical to rounding at staging. Measured on gfx1151: ffn-down (k = 9216) 13.5 -> 23.5 TFLOPS at
   n = 512 once B plus the weights no longer fit the 32 MB Infinity Cache; neutral for small k.

Re-run after editing a base shader:

    python native/vulkan/gen_splitk_variants.py
"""
import pathlib
import re

SHADERS = pathlib.Path(__file__).parent / "shaders"
QUANTS = ["q4_k", "q5_k", "q6_k", "q8_0"]
NL = chr(10)


def read(path):
    return path.read_bytes().decode("utf-8", errors="surrogateescape")


def write(path, text):
    path.write_bytes(text.encode("utf-8", errors="surrogateescape"))
    print("wrote", path.name)


def with_banner(text, banner_lines):
    first_line_end = text.index(NL) + 1   # keep '#version' first
    return text[:first_line_end] + NL.join(banner_lines) + NL + text[first_line_end:]


# ---- 1. split-K twins -------------------------------------------------------------------------------------------------
for q in QUANTS:
    base = SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4.comp"
    out = read(base)

    marker = "    uint rowUints;"
    assert out.count(marker) == 1, f"{base.name}: expected exactly one rowUints push constant"
    out = out.replace(marker, marker + NL + "    uint chunksPerSplit;  // BK=32 chunks owned by each z-slice (split-K)", 1)

    m = re.search(r"^#define GEMM_CHUNKS .*$", out, re.M)
    assert m, f"{base.name}: no GEMM_CHUNKS define"
    out = out[:m.end()] + NL + "#define GEMM_SPLITK" + NL + "#define GEMM_CHUNKS_PER_SPLIT pc.chunksPerSplit" + out[m.end():]

    out = with_banner(out, [
        f"// SPLIT-K TWIN of {base.name} -- GENERATED by native/vulkan/gen_splitk_variants.py, do not edit.",
        "// gl_WorkGroupID.z selects a K slice and a private C slab; splitk_reduce_f32.comp sums the slabs.",
    ])
    write(SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4_splitk.comp", out)

# ---- 2. F16-activation variants ---------------------------------------------------------------------------------------
B_DECL = re.compile(r"buffer BufB \{ vec4 b4\[\]; \};")
INCLUDE_EXT = "#extension GL_GOOGLE_include_directive : require"
for q in QUANTS:
    for suffix in ("", "_splitk"):
        src = SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4{suffix}.comp"
        text = read(src)
        m = B_DECL.search(text)
        assert m, f"{src.name}: no vec4 BufB declaration"
        out = text[:m.start()] + "buffer BufB { f16vec4 b4[]; };" + text[m.end():]
        assert out.count("#define GEMM_B_VEC4") == 1, f"{src.name}: expected one GEMM_B_VEC4 define"
        out = out.replace("#define GEMM_B_VEC4", "#define GEMM_B_VEC4" + NL + "#define GEMM_B_FETCH(i) vec4(b4[i])", 1)
        assert out.count(INCLUDE_EXT) == 1, f"{src.name}: include-directive extension line"
        out = out.replace(INCLUDE_EXT, INCLUDE_EXT + NL
                          + "#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require" + NL
                          + "#extension GL_EXT_shader_16bit_storage : require", 1)
        out = with_banner(out, [
            f"// F16-ACTIVATION VARIANT of {src.name} -- GENERATED by native/vulkan/gen_splitk_variants.py, do not edit.",
            "// B is f16vec4[] (the producer rounds to F16 once); the K loop and A staging are unchanged.",
        ])
        write(SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4_bh{suffix}.comp", out)
