#!/usr/bin/env python3
"""Generates the indexed MoE IQ MMVQ decode shaders (issue #823) from the dense matmul_iq*_mmvq.comp shaders.

The dense kernels already have the right lane layout (one wave32 subgroup per output row, dp4a against a Q8_1 activation); an expert-bank
kernel differs only by (a) a per-row expert index buffer, (b) a 2-D grid (m, n), (c) the row base offset by expert * M rows and the
activation / output rows by n. This script applies exactly those textual changes so the two families cannot drift.

Bindings of the generated shaders: 0 bank, 1 xq, 2 xds, 3 indices, 4 y, 5.. codebooks (dense had y at 3 and codebooks from 4).

Run from the repo root: python native/vulkan/gen_moe_indexed_iq.py
"""
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
SHADERS = os.path.join(HERE, 'shaders')

# dense shader -> (generated name, display name)
TARGETS = [
    ('matmul_iq2_xxs_mmvq', 'moe_indexed_matmul_iq2_xxs_mmvq', 'IQ2_XXS'),
    ('matmul_iq2_xs_mmvq', 'moe_indexed_matmul_iq2_xs_mmvq', 'IQ2_XS'),
    ('matmul_iq2_s_mmvq', 'moe_indexed_matmul_iq2_s_mmvq', 'IQ2_S'),
    ('matmul_iq3_xxs_mmvq', 'moe_indexed_matmul_iq3_xxs_mmvq', 'IQ3_XXS'),
]


def sub1(s, pattern, repl, flags=0):
    new, n = re.subn(pattern, repl, s, count=1, flags=flags)
    assert n == 1, pattern
    return new


def convert(dense_name, out_name, fmt):
    s = open(os.path.join(SHADERS, dense_name + '.comp'), newline='', encoding='utf-8').read().replace('\r\n', '\n')

    banner = (f'// MoE INDEXED {fmt} MMVQ decode GEMV (issue #823), GENERATED by native/vulkan/gen_moe_indexed_iq.py from {dense_name}.comp -\n'
              '// edit the generator / the dense shader, not this file. Same lane layout and dp4a math as the dense kernel over a packed expert bank:\n'
              '//   y[n, m] = sum_k dequant(bank[indices[n], m, k]) * x[n, k]\n'
              '// 2-D dispatch: gl_WorkGroupID.x = m, gl_WorkGroupID.y = n. Bindings: 0 bank, 1 xq, 2 xds, 3 indices, 4 y, then the codebook buffers.\n')
    s = s.replace('#version 450\n', '#version 450\n', 1)
    # banner after the extension block: put right after the last #extension line
    lines = s.split('\n')
    last_ext = max(i for i, l in enumerate(lines) if l.startswith('#extension'))
    lines.insert(last_ext + 1, banner.rstrip('\n'))
    s = '\n'.join(lines)

    # bindings: shift y and codebooks, add indices
    s = sub1(s, r'layout\(set = 0, binding = 3, std430\) writeonly buffer BufY\s*\{ float y\[\]; \};',
             'layout(set = 0, binding = 3, std430) readonly  buffer BufIdx    { int   indices[]; };\n'
             'layout(set = 0, binding = 4, std430) writeonly buffer BufY      { float y[]; };')
    s = sub1(s, r'binding = 5, std430\) readonly  buffer BufKsigns', 'binding = 6, std430) readonly  buffer BufKsigns') if 'BufKsigns' in s else s
    s = sub1(s, r'binding = 4, std430\) readonly  buffer BufGrid', 'binding = 5, std430) readonly  buffer BufGrid')

    # push constants
    s = sub1(s, r'layout\(push_constant\) uniform PushConstants \{.*?\} pc;',
             'layout(push_constant) uniform PushConstants {\n    uint M;\n    uint K;\n    uint N;\n    uint numExperts;\n    uint blocksPerRow; // K / 256\n    uint xDiv;          // activation row = n / xDiv (1 = per-row input; topK = one row broadcast to its topK expert slots)\n} pc;',
             re.S)

    # entry: m / n / expert
    s = sub1(s, r'    uint m = gl_WorkGroupID.x;\n    if \(m >= pc.M\) return;\n',
             '    uint m = gl_WorkGroupID.x;\n    uint n = gl_WorkGroupID.y;\n    if (m >= pc.M || n >= pc.N) return;\n\n'
             '    uint expert = uint(indices[n]);\n    if (expert >= pc.numExperts) return; // defensive: bad index leaves y untouched\n')
    s = sub1(s, r'    uint rowByteBase = m \* pc.blocksPerRow \* (\w+_BLOCK_BYTES);',
             r'    uint rowByteBase = (expert * pc.M + m) * pc.blocksPerRow * \1;\n    uint xRow        = n / pc.xDiv;\n    uint xqRowBase   = xRow * (pc.K >> 2u);\n    uint xdsRowBase  = xRow * (pc.K >> 5u);')
    s = sub1(s, r'uint xqi = blk \* 64u', 'uint xqi = xqRowBase + blk * 64u')
    s = sub1(s, r'xds\[blk \* 8u \+ ib32\]', 'xds[xdsRowBase + blk * 8u + ib32]')
    s = sub1(s, r'y\[m\] = total;', 'y[n * pc.M + m] = total;')
    return s


def main():
    for dense, out, fmt in TARGETS:
        text = convert(dense, out, fmt)
        path = os.path.join(SHADERS, out + '.comp')
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(text)
        print('wrote', path)


if __name__ == '__main__':
    main()
