#!/usr/bin/env python3
"""Generates the grouped MoE IQ coopmat prefill shaders (issue #823): native/vulkan/shaders/moe_grouped_matmul_iq*_coopmat_m64.comp.

Each shader is the moe_grouped_matmul_mxfp4_coopmat_m64.comp skeleton (16x16 tiles x 4 wave64 subgroups = 64 weight rows per workgroup, one
shared B tile, 64 K = two 32-element blocks per staging round, register-prefetched K loop, indirect tile-list contract) with a per-format
`Stage` struct, `loadStage` (raw weight words) and `commitStage` (dequantise this thread's 16 elements into the F16 A tile).

Run from the repo root: python native/vulkan/gen_moe_grouped_iq.py
"""
import os

HEADER = r'''#version 450
// GENERATED by native/vulkan/gen_moe_grouped_iq.py (issue #823) - edit the generator, not this file.
// Grouped __FMT__ MoE expert matmul via VK_KHR_cooperative_matrix, 16x16 tiles x 4 subgroups (64 output rows per workgroup, one shared B tile),
// 64 K (two 32-element blocks) per staging round.
//
//   Y[packedRow, m] = X[packedRow, :] @ W___LOWER__[expert, m, :]^T      (W dequantised into the F16 A operand on the fly)
//
// Rows are grouped by expert (offsets[expert]..offsets[expert+1]); same dispatch / tile-list contract as moe_grouped_matmul_q5_1_coopmat_m64.comp.
// __LAYOUT__
// Row stride is passed in BYTES (pc.rowBytes). PRECISION: the dequantised weight is folded into the F16 A operand (~2^-11), as in every
// grouped shader here. K must be a multiple of __KREQ__ (64 = one staging round).

#extension GL_KHR_cooperative_matrix      : require
#extension GL_KHR_memory_scope_semantics  : require
#extension GL_KHR_shader_subgroup_basic   : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require
#extension GL_EXT_shader_16bit_storage    : require
#extension GL_EXT_control_flow_attributes : require

layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0, std430) readonly  buffer BufW       { uint weight[]; };
layout(set = 0, binding = 1, std430) readonly  buffer BufX       { vec4 x4[]; };      // [rows,K] F32 (K % 4 == 0)
layout(set = 0, binding = 2, std430) readonly  buffer BufOffsets { uint offsets[]; }; // [E+1] (+ tile list)
layout(set = 0, binding = 3, std430) writeonly buffer BufY       { float y[]; };      // [rows,M] F32
__EXTRA_BINDINGS__
layout(push_constant) uniform PushConstants {
    uint M;
    uint K;
    uint rows;
    uint numExperts;
    uint blocksPerRow;  // K / 32
    uint rowBytes;      // per-row BYTE stride
    uint tileList;      // 0 = legacy 3-D grid; else index in `offsets` of the tile work list (indirect mode)
    uint applyScale;    // unused (kept so the push-constant block matches the other grouped shaders)
} pc;

const uint TM = 16u;
const uint TN = 16u;
const uint TK = 16u;
const uint SB = 64u;                // K per staging round (two blocks)
const uint STRIDE = SB + 8u;        // padded LDS row stride (halves)
const uint NSG = 4u;
const uint WAVE = 64u;
const uint WG_THREADS = 256u;

shared float16_t sharedA[NSG * TM * STRIDE];
shared float16_t sharedB[TN * STRIDE];
shared float storeStage[NSG * TM * TN];

uint readByte(uint absByteOff) {
    return (weight[absByteOff >> 2u] >> ((absByteOff & 3u) * 8u)) & 0xFFu;
}

uint readHalfBits(uint absByteOff) {
    uint idx = absByteOff >> 2u;
    uint ph = absByteOff & 3u;
    uint u = weight[idx];
    if (ph <= 2u) return (u >> (ph * 8u)) & 0xFFFFu;
    return ((u >> 24) & 0xFFu) | ((weight[idx + 1u] & 0xFFu) << 8);
}
'''

KV = r'''const int KV[16] = int[16](
    -127, -104, -83, -65, -49, -35, -22, -10,
       1,   13,  25,  38,  53,  69,  89, 113
);
'''

B_COMMIT = r'''    uint bRow = tid >> 4u;
    uint c4 = tid & 15u;
    uint o = bRow * STRIDE + c4 * 4u;
    sharedB[o]      = float16_t(st.bv.x);
    sharedB[o + 1u] = float16_t(st.bv.y);
    sharedB[o + 2u] = float16_t(st.bv.z);
    sharedB[o + 3u] = float16_t(st.bv.w);
}
'''

B_LOAD = r'''    uint bRow = tid >> 4u;
    uint c4 = tid & 15u;
    st.bv = (localRowBase + bRow) < expertRows ? x4[xRowBase4 + bRow * (pc.K / 4u) + sb * (SB / 4u) + c4] : vec4(0.0);
}
'''

MAIN = r'''
void main() {
    uint mBase = gl_WorkGroupID.x * (TM * NSG);
    uint localRowBase;
    uint expert;
    if (pc.tileList != 0u) {
        // Indirect mode (moe_build_tile_list.comp): workgroup y is a tile index into the work list stored in `offsets` from
        // pc.tileList on; only real (expert, row tile) pairs are launched.
        uint listIdx = pc.tileList + 2u * gl_WorkGroupID.y;
        expert = offsets[listIdx];
        localRowBase = offsets[listIdx + 1u];
    } else {
        localRowBase = gl_WorkGroupID.y * TN;
        expert = gl_WorkGroupID.z;
        if (expert >= pc.numExperts) return;
    }

    uint expertStart = offsets[expert];
    uint expertRows = offsets[expert + 1u] - expertStart;
    if (localRowBase >= expertRows) return;

    uint tid = gl_LocalInvocationID.x;
    uint sg = tid >> 6u;                // which subgroup / M tile
    uint lane64 = tid & 63u;

    coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator> sums =
        coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator>(0.0);

    uint mLocal = lane64 / 4u;          // weight row of this thread within its subgroup tile
    uint lane = lane64 - mLocal * 4u;   // 0..3: block (lane >> 1) of the round, half (lane & 1) of that block
    uint blk = lane >> 1u;
    uint half_ = lane & 1u;
    uint mGlobal = mBase + sg * TM + mLocal;
    bool rowValid = mGlobal < pc.M;
    uint rowBase = expert * pc.M * pc.rowBytes + mGlobal * pc.rowBytes;
    uint xRowBase4 = (expertStart + localRowBase) * (pc.K / 4u);

    // Register-prefetched K loop (see moe_grouped_matmul_q5_1_coopmat_m64.comp): round sb+1's raw weight words and activation vec4s are
    // loaded right after the staging barrier and only converted / stored to LDS after sb's MMAs.
    Stage st;
    loadStage(0u, tid, blk, half_, rowValid, rowBase, xRowBase4, localRowBase, expertRows, st);

    for (uint sb = 0u; sb < pc.K / SB; sb++) {
        commitStage(st, tid, sg, mLocal, blk, half_, rowValid);

        barrier();
        memoryBarrierShared();

        if ((sb + 1u) < pc.K / SB)
            loadStage(sb + 1u, tid, blk, half_, rowValid, rowBase, xRowBase4, localRowBase, expertRows, st);

        for (uint kSlice = 0u; kSlice < SB; kSlice += TK) {
            coopmat<float16_t, gl_ScopeSubgroup, TM, TK, gl_MatrixUseA> aTile;
            coopmat<float16_t, gl_ScopeSubgroup, TK, TN, gl_MatrixUseB> bTile;

            coopMatLoad(aTile, sharedA, sg * TM * STRIDE + kSlice, STRIDE, gl_CooperativeMatrixLayoutRowMajor);
            coopMatLoad(bTile, sharedB, kSlice, STRIDE, gl_CooperativeMatrixLayoutColumnMajor);
            sums = coopMatMulAdd(aTile, bTile, sums);
        }

        barrier();
    }

    coopMatStore(sums, storeStage, sg * TM * TN, TM, gl_CooperativeMatrixLayoutColumnMajor);
    barrier();

    for (uint i = 0u; i < 4u; i++) {
        uint idx = lane64 + i * WAVE;
        if (idx >= TM * TN) break;
        uint localRowInTile = idx / TM;
        uint m = idx - localRowInTile * TM;
        uint lr = localRowBase + localRowInTile;
        uint mG = mBase + sg * TM + m;
        if (lr < expertRows && mG < pc.M) {
            uint packedRow = expertStart + lr;
            y[packedRow * pc.M + mG] = storeStage[sg * TM * TN + localRowInTile * TM + m];
        }
    }
}
'''

LOAD_SIG = 'void loadStage(uint sb, uint tid, uint blk, uint half_, bool rowValid, uint rowBase, uint xRowBase4, uint localRowBase, uint expertRows, inout Stage st) {\n'
COMMIT_SIG = 'void commitStage(in Stage st, uint tid, uint sg, uint mLocal, uint blk, uint half_, bool rowValid) {\n    uint aBase = sg * TM * STRIDE + mLocal * STRIDE + blk * 32u + half_ * 16u;\n'
ZERO_A = '''    if (!rowValid) {
        for (uint j = 0u; j < 16u; j++) sharedA[aBase + j] = float16_t(0.0);
    } else {
'''

# ---------------------------------------------------------------------------------------------------------------------------------
# IQ4_NL: 18-byte blocks (fp16 d, 16 nibble bytes). Block pairs are word aligned only every second block -> funnel-shift 5 words.
IQ4_NL = dict(
    name='iq4_nl', fmt='IQ4_NL', kreq='64', extra='',
    layout='Bank layout: [E, M, K/32 blocks of 18 bytes]: fp16 d, qs[16] (low nibble of byte j = element j, high nibble = element j + 16);\n// value = d * kvalues_iq4nl[nibble]. Blocks are 18 bytes (not word aligned): each thread loads the 5 words covering its block and funnel-shifts them.',
    body=KV + '''const uint IQ4_NL_BLOCK_BYTES = 18u;

struct Stage { uint aw[5]; vec4 bv; };   // aw: the block's 18 bytes realigned to byte 0 (d in aw[0] bits 0..15, qs bytes 2..17)

''' + LOAD_SIG + '''    for (uint i = 0u; i < 5u; i++) st.aw[i] = 0u;
    if (rowValid) {
        uint off = rowBase + (sb * 2u + blk) * IQ4_NL_BLOCK_BYTES;
        uint wi = off >> 2u;
        uint sh = (off & 3u) * 8u;
        uint w0 = weight[wi], w1 = weight[wi + 1u], w2 = weight[wi + 2u], w3 = weight[wi + 3u], w4 = weight[wi + 4u];
        if (sh == 0u) {
            st.aw[0] = w0; st.aw[1] = w1; st.aw[2] = w2; st.aw[3] = w3; st.aw[4] = w4;
        } else {
            uint rs = 32u - sh;
            st.aw[0] = (w0 >> sh) | (w1 << rs);
            st.aw[1] = (w1 >> sh) | (w2 << rs);
            st.aw[2] = (w2 >> sh) | (w3 << rs);
            st.aw[3] = (w3 >> sh) | (w4 << rs);
            st.aw[4] = w4 >> sh;
        }
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.aw[0] & 0xFFFFu).x;
        // qs bytes are block bytes 2..17; this thread's half selects the low (elements 0..15) or high (16..31) nibbles.
        uint shift = half_ * 4u;
        for (uint w = 0u; w < 4u; w++) {
            uint nw = (st.aw[w] >> 16u) | (st.aw[w + 1u] << 16u);
            for (uint jb = 0u; jb < 4u; jb++) {
                uint nib = (nw >> (jb * 8u + shift)) & 0xFu;
                sharedA[aBase + w * 4u + jb] = float16_t(d * float(KV[nib]));
            }
        }
    }
''' + B_COMMIT)

# ---------------------------------------------------------------------------------------------------------------------------------
# IQ4_XS: 136-byte super-blocks (word aligned): d, scales_h, scales_l[4], qs[128]; sub-block s = ib32 of the super-block.
IQ4_XS = dict(
    name='iq4_xs', fmt='IQ4_XS', kreq='256', extra='',
    layout='Bank layout: [E, M, K/256 super-blocks of 136 bytes]: fp16 d, u16 scales_h, u8 scales_l[4], qs[128] (8 sub-blocks x 16 bytes, low nibble of byte j = element j,\n// high nibble = element j + 16); value = d * (ls - 32) * kvalues_iq4nl[nibble], ls = 4 low bits (scales_l) | 2 high bits (scales_h). Super-blocks are 4-byte aligned.',
    body='')

# (body assigned below once the sub-block index is carried through the Stage)

# IQ4_XS needs the sub-block index in commitStage for the scale nibble; pass it through the Stage instead (ib).
IQ4_XS['body'] = KV + '''const uint IQ4_XS_BLOCK_BYTES = 136u;

struct Stage { uint aw[6]; uint ib; vec4 bv; };   // aw[0]: d | scales_h<<16, aw[1]: scales_l, aw[2..5]: this sub-block's 16 qs bytes; ib: sub-block in its super-block

''' + LOAD_SIG + '''    for (uint i = 0u; i < 6u; i++) st.aw[i] = 0u;
    st.ib = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;            // 32-element sub-block index along K
        uint base = rowBase + (s >> 3u) * IQ4_XS_BLOCK_BYTES;
        uint ib = s & 7u;
        st.ib = ib;
        uint wi = base >> 2u;
        st.aw[0] = weight[wi];
        st.aw[1] = weight[wi + 1u];
        uint q = wi + 2u + ib * 4u;
        st.aw[2] = weight[q]; st.aw[3] = weight[q + 1u]; st.aw[4] = weight[q + 2u]; st.aw[5] = weight[q + 3u];
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.aw[0] & 0xFFFFu).x;
        uint scalesH = st.aw[0] >> 16u;
        uint ib = st.ib;
        uint low = (st.aw[1] >> (8u * (ib >> 1u) + 4u * (ib & 1u))) & 0xFu;
        uint high = (scalesH >> (2u * ib)) & 0x3u;
        float dl = d * float(int(low | (high << 4u)) - 32);
        uint shift = half_ * 4u;
        for (uint w = 0u; w < 4u; w++) {
            uint nw = st.aw[2u + w];
            for (uint jb = 0u; jb < 4u; jb++) {
                uint nib = (nw >> (jb * 8u + shift)) & 0xFu;
                sharedA[aBase + w * 4u + jb] = float16_t(dl * float(KV[nib]));
            }
        }
    }
''' + B_COMMIT

# ---------------------------------------------------------------------------------------------------------------------------------
# IQ3_S: 110-byte super-blocks (NOT word aligned): d, qs[64], qh[8], signs[32], scales[4]; grid in an SSBO (512 x 4 magnitude bytes).
IQ3_S = dict(
    name='iq3_s', fmt='IQ3_S', kreq='256',
    extra='layout(set = 0, binding = 4, std430) readonly  buffer BufGrid { uint iq3sGrid[]; };  // 512 x uint32 (4 grid magnitude bytes each)\n',
    layout='Bank layout: [E, M, K/256 super-blocks of 110 bytes]: fp16 d, qs[64], qh[8], signs[32], scales[4]. Sub-block ib32 (32 elements) = 4 pairs of 8: pair l reads\n// qs[ib32*8 + 2l .. +1] (+ one qh bit each) as two 9-bit iq3s grid indices (4 magnitude bytes each) and sign byte signs[ib32*4 + l] (bit e = negate element e);\n// value = d * (1 + 2 * sub_scale) * sign * grid byte. This thread owns pairs 2*half_ and 2*half_+1 (16 elements).',
    body='''const uint IQ3_S_BLOCK_BYTES = 110u;

struct Stage { uint dq; uint qs4; uint sg2; uint misc; vec4 bv; };   // dq: d bits | ib32<<16; qs4: 4 qs bytes; sg2: 2 sign bytes; misc: qh | scaleByte<<8

''' + LOAD_SIG + '''    st.dq = 0u; st.qs4 = 0u; st.sg2 = 0u; st.misc = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;            // 32-element sub-block index along K
        uint base = rowBase + (s >> 3u) * IQ3_S_BLOCK_BYTES;
        uint ib32 = s & 7u;
        uint d = readHalfBits(base);
        uint qso = base + 2u + ib32 * 8u + half_ * 4u;
        st.qs4 = readByte(qso) | (readByte(qso + 1u) << 8u) | (readByte(qso + 2u) << 16u) | (readByte(qso + 3u) << 24u);
        uint sgo = base + 74u + ib32 * 4u + half_ * 2u;
        st.sg2 = readByte(sgo) | (readByte(sgo + 1u) << 8u);
        st.misc = readByte(base + 66u + ib32) | (readByte(base + 106u + (ib32 >> 1u)) << 8u);
        st.dq = d | (ib32 << 16u);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.dq & 0xFFFFu).x;
        uint ib32 = st.dq >> 16u;
        uint qh = st.misc & 0xFFu;
        uint scaleByte = (st.misc >> 8u) & 0xFFu;
        uint sub = ((ib32 & 1u) == 0u) ? (scaleByte & 0xFu) : (scaleByte >> 4u);
        float db = d * float(1u + 2u * sub);
        for (uint pl = 0u; pl < 2u; pl++) {
            uint l = half_ * 2u + pl;                       // pair within the sub-block (0..3)
            uint g1 = ((st.qs4 >> (16u * pl)) & 0xFFu) | ((qh << (8u - 2u * l)) & 0x100u);
            uint g2 = ((st.qs4 >> (16u * pl + 8u)) & 0xFFu) | ((qh << (7u - 2u * l)) & 0x100u);
            uint sgn = (st.sg2 >> (8u * pl)) & 0xFFu;
            uint ga = iq3sGrid[g1];
            uint gb = iq3sGrid[g2];
            for (uint e = 0u; e < 4u; e++) {
                float va = db * float((ga >> (8u * e)) & 0xFFu);
                float vb = db * float((gb >> (8u * e)) & 0xFFu);
                sharedA[aBase + pl * 8u + e]      = float16_t(((sgn >> e) & 1u) != 0u ? -va : va);
                sharedA[aBase + pl * 8u + 4u + e] = float16_t(((sgn >> (4u + e)) & 1u) != 0u ? -vb : vb);
            }
        }
    }
''' + B_COMMIT)


READ4 = r'''uint read4Bytes(uint absByteOff) {
    uint idx = absByteOff >> 2u;
    uint ph  = absByteOff & 3u;
    uint lo  = weight[idx];
    if (ph == 0u) return lo;
    uint hi = weight[idx + 1u];
    return (lo >> (ph * 8u)) | (hi << ((4u - ph) * 8u));
}

'''

# ---------------------------------------------------------------------------------------------------------------------------------
# Shared by the IQ2 / IQ3_XXS formats: one 8-element pair = two grid words (IQ2: bytes 0..3 / 4..7 of one 8-byte entry; IQ3: two 4-byte
# entries) + an 8-bit sign mask + a scale.
PAIR8 = r'''void emitPair8(uint dst, uint wa, uint wb, uint signs, float sc) {
    for (uint e = 0u; e < 4u; e++) {
        float va = sc * float((wa >> (8u * e)) & 0xFFu);
        float vb = sc * float((wb >> (8u * e)) & 0xFFu);
        sharedA[dst + e]      = float16_t(((signs >> e) & 1u) != 0u ? -va : va);
        sharedA[dst + 4u + e] = float16_t(((signs >> (4u + e)) & 1u) != 0u ? -vb : vb);
    }
}

'''

# IQ2_XXS: 66-byte super-blocks: d, then per sub-block 8 bytes a0 (4 grid-index bytes) + a1 (4 x 7-bit sign indices in the low 28 bits, scale in the top nibble).
IQ2_XXS = dict(
    name='iq2_xxs', fmt='IQ2_XXS', kreq='256',
    extra=('layout(set = 0, binding = 4, std430) readonly  buffer BufGrid   { uint iq2xxsGrid[]; };   // 256 entries x 8 magnitude bytes\n'
           'layout(set = 0, binding = 5, std430) readonly  buffer BufKsigns { uint ksigns[]; };       // 128 sign bytes\n'),
    layout='Bank layout: [E, M, K/256 super-blocks of 66 bytes]: fp16 d, then per 32-element sub-block 8 bytes a0 (4 grid indices) + a1 (4 x 7-bit ksigns indices | 4-bit scale << 28);\n// pair l (8 elements) = iq2xxs grid entry (a0 >> 8l) & 255 with sign byte ksigns[(a1 >> 7l) & 127]; value = d * (0.5 + (a1 >> 28)) * 0.25 * sign * grid byte.',
    body='''const uint IQ2_XXS_BLOCK_BYTES = 66u;

struct Stage { uint dq; uint a0; uint a1; vec4 bv; };   // dq: d bits

''' + READ4 + PAIR8 + LOAD_SIG + '''    st.dq = 0u; st.a0 = 0u; st.a1 = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;
        uint base = rowBase + (s >> 3u) * IQ2_XXS_BLOCK_BYTES;
        uint ib32 = s & 7u;
        st.dq = readHalfBits(base);
        uint p = base + 2u + 8u * ib32;
        st.a0 = read4Bytes(p);
        st.a1 = read4Bytes(p + 4u);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.dq & 0xFFFFu).x;
        float db = d * (0.5 + float(st.a1 >> 28)) * 0.25;
        for (uint pl = 0u; pl < 2u; pl++) {
            uint l = half_ * 2u + pl;
            uint gridIdx = (st.a0 >> (8u * l)) & 0xFFu;
            uint signs = (ksigns[((st.a1 >> (7u * l)) & 0x7Fu) >> 2u] >> ((((st.a1 >> (7u * l)) & 0x7Fu) & 3u) * 8u)) & 0xFFu;
            emitPair8(aBase + pl * 8u, iq2xxsGrid[gridIdx * 2u], iq2xxsGrid[gridIdx * 2u + 1u], signs, db);
        }
    }
''' + B_COMMIT)

# IQ2_XS: 74-byte super-blocks: d, qs[32] uint16 (9-bit grid | 7-bit ksigns index << 9), scales[8] (two nibbles per byte).
IQ2_XS = dict(
    name='iq2_xs', fmt='IQ2_XS', kreq='256',
    extra=('layout(set = 0, binding = 4, std430) readonly  buffer BufGrid   { uint iq2xsGrid[]; };    // 512 entries x 8 magnitude bytes\n'
           'layout(set = 0, binding = 5, std430) readonly  buffer BufKsigns { uint ksigns[]; };       // 128 sign bytes\n'),
    layout='Bank layout: [E, M, K/256 super-blocks of 74 bytes]: fp16 d, qs[32] uint16 (low 9 bits = iq2xs grid index, high 7 bits = ksigns index), scales[8];\n// pair l of sub-block ib32 = qs[ib32*4 + l]; scale nibble = scales[ib32] low (l < 2) / high (l >= 2); value = d * (0.5 + sub) * 0.25 * sign * grid byte.',
    body='''const uint IQ2_XS_BLOCK_BYTES = 74u;

struct Stage { uint dq; uint q2; uint sc; vec4 bv; };   // dq: d bits; q2: the two uint16 of this half; sc: scale byte

''' + READ4 + PAIR8 + LOAD_SIG + '''    st.dq = 0u; st.q2 = 0u; st.sc = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;
        uint base = rowBase + (s >> 3u) * IQ2_XS_BLOCK_BYTES;
        uint ib32 = s & 7u;
        st.dq = readHalfBits(base);
        st.q2 = read4Bytes(base + 2u + ib32 * 8u + half_ * 4u);
        st.sc = readByte(base + 66u + ib32);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.dq & 0xFFFFu).x;
        uint sub = half_ == 0u ? (st.sc & 0xFu) : (st.sc >> 4u);
        float dl = d * (0.5 + float(sub)) * 0.25;
        for (uint pl = 0u; pl < 2u; pl++) {
            uint q = (st.q2 >> (16u * pl)) & 0xFFFFu;
            uint gridIdx = q & 0x1FFu;
            uint si = q >> 9u;
            uint signs = (ksigns[si >> 2u] >> ((si & 3u) * 8u)) & 0xFFu;
            emitPair8(aBase + pl * 8u, iq2xsGrid[gridIdx * 2u], iq2xsGrid[gridIdx * 2u + 1u], signs, dl);
        }
    }
''' + B_COMMIT)

# IQ2_S: 82-byte super-blocks: d, qs[32] (grid low 8 bits), qs_signs[32] (explicit sign byte), qh[8] (2 high grid bits per pair), scales[8].
IQ2_S = dict(
    name='iq2_s', fmt='IQ2_S', kreq='256',
    extra='layout(set = 0, binding = 4, std430) readonly  buffer BufGrid { uint iq2sGrid[]; };   // 1024 entries x 8 magnitude bytes\n',
    layout='Bank layout: [E, M, K/256 super-blocks of 82 bytes]: fp16 d, qs[32] (grid index low 8 bits), qs_signs[32] (explicit 8-bit sign mask), qh[8], scales[8];\n// pair l of sub-block ib32: grid = qs[ib32*4+l] | ((qh[ib32] >> 2l) & 3) << 8, sign byte qs_signs[ib32*4+l]; scale nibble = scales[ib32] low (l < 2) / high; value = d * (0.5 + sub) * 0.25 * sign * grid byte.',
    body='''const uint IQ2_S_BLOCK_BYTES = 82u;

struct Stage { uint dq; uint lo2; uint sg2; uint qhs; vec4 bv; };   // dq: d bits; lo2: 2 grid-low bytes; sg2: 2 sign bytes; qhs: qh | scaleByte << 8

''' + PAIR8 + LOAD_SIG + '''    st.dq = 0u; st.lo2 = 0u; st.sg2 = 0u; st.qhs = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;
        uint base = rowBase + (s >> 3u) * IQ2_S_BLOCK_BYTES;
        uint ib32 = s & 7u;
        st.dq = readHalfBits(base);
        uint lo = base + 2u + ib32 * 4u + half_ * 2u;
        st.lo2 = readByte(lo) | (readByte(lo + 1u) << 8u);
        uint sg = base + 34u + ib32 * 4u + half_ * 2u;
        st.sg2 = readByte(sg) | (readByte(sg + 1u) << 8u);
        st.qhs = readByte(base + 66u + ib32) | (readByte(base + 74u + ib32) << 8u);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.dq & 0xFFFFu).x;
        uint qh = st.qhs & 0xFFu;
        uint sb8 = (st.qhs >> 8u) & 0xFFu;
        uint sub = half_ == 0u ? (sb8 & 0xFu) : (sb8 >> 4u);
        float dl = d * (0.5 + float(sub)) * 0.25;
        for (uint pl = 0u; pl < 2u; pl++) {
            uint l = half_ * 2u + pl;
            uint gridIdx = ((st.lo2 >> (8u * pl)) & 0xFFu) | (((qh >> (2u * l)) & 3u) << 8u);
            uint signs = (st.sg2 >> (8u * pl)) & 0xFFu;
            emitPair8(aBase + pl * 8u, iq2sGrid[gridIdx * 2u], iq2sGrid[gridIdx * 2u + 1u], signs, dl);
        }
    }
''' + B_COMMIT)

# IQ3_XXS: 98-byte super-blocks: d, qs[64] grid bytes (g1,g2 per pair), scales_and_signs[8] uint32 (4 x 7-bit ksigns | scale << 28).
IQ3_XXS = dict(
    name='iq3_xxs', fmt='IQ3_XXS', kreq='256',
    extra=('layout(set = 0, binding = 4, std430) readonly  buffer BufGrid   { uint iq3xxsGrid[]; };   // 256 entries x 4 magnitude bytes\n'
           'layout(set = 0, binding = 5, std430) readonly  buffer BufKsigns { uint ksigns[]; };       // 128 sign bytes\n'),
    layout='Bank layout: [E, M, K/256 super-blocks of 98 bytes]: fp16 d, qs[64] (8-bit grid indices: g1, g2 per pair), scales_and_signs[8] uint32 (4 x 7-bit ksigns | scale << 28);\n// pair l of sub-block ib32: g1 = qs[ib32*8 + 2l], g2 = qs[ib32*8 + 2l + 1] (4 magnitude bytes each), sign byte ksigns[(aux >> 7l) & 127]; value = d * (0.5 + (aux >> 28)) * 0.5 * sign * grid byte.',
    body='''const uint IQ3_XXS_BLOCK_BYTES = 98u;

struct Stage { uint dq; uint qs4; uint aux; vec4 bv; };   // dq: d bits; qs4: this half's 4 grid-index bytes; aux: scales_and_signs of the sub-block

''' + READ4 + PAIR8 + LOAD_SIG + '''    st.dq = 0u; st.qs4 = 0u; st.aux = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;
        uint base = rowBase + (s >> 3u) * IQ3_XXS_BLOCK_BYTES;
        uint ib32 = s & 7u;
        st.dq = readHalfBits(base);
        st.qs4 = read4Bytes(base + 2u + ib32 * 8u + half_ * 4u);
        st.aux = read4Bytes(base + 66u + 4u * ib32);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.dq & 0xFFFFu).x;
        float db = d * (0.5 + float(st.aux >> 28)) * 0.5;
        for (uint pl = 0u; pl < 2u; pl++) {
            uint l = half_ * 2u + pl;
            uint g1 = (st.qs4 >> (16u * pl)) & 0xFFu;
            uint g2 = (st.qs4 >> (16u * pl + 8u)) & 0xFFu;
            uint si = (st.aux >> (7u * l)) & 0x7Fu;
            uint signs = (ksigns[si >> 2u] >> ((si & 3u) * 8u)) & 0xFFu;
            emitPair8(aBase + pl * 8u, iq3xxsGrid[g1], iq3xxsGrid[g2], signs, db);
        }
    }
''' + B_COMMIT)

# Q2_0 (upstream ggml): 18-byte blocks of 64 elements = exactly one 64-K staging round. Thread (blk, half_) owns elements [32*blk + 16*half_, +16).
Q2_0 = dict(
    name='q2_0', fmt='Q2_0', kreq='64', extra='',
    layout='Bank layout: [E, M, K/64 blocks of 18 bytes]: fp16 d, qs[16] 2-bit codes (element j = qs[j/4] >> 2(j%4) & 3); value = (code - 1) * d. One block = one staging round;\n// this thread owns the 4 code bytes of its 16 elements (block byte 2 + 8*blk + 4*half_, an even offset).',
    body='''const uint Q2_0_BLOCK_BYTES = 18u;

struct Stage { uint d; uint codes; vec4 bv; };   // d: fp16 bits; codes: this thread's 4 code bytes (16 two-bit codes)

''' + LOAD_SIG + '''    st.d = 0u; st.codes = 0u;
    if (rowValid) {
        uint base = rowBase + sb * Q2_0_BLOCK_BYTES;
        st.d = readHalfBits(base);
        uint cb = base + 2u + 8u * blk + 4u * half_;
        st.codes = readHalfBits(cb) | (readHalfBits(cb + 2u) << 16u);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        float d = unpackHalf2x16(st.d & 0xFFFFu).x;
        for (uint j = 0u; j < 16u; j++)
            sharedA[aBase + j] = float16_t(float(int((st.codes >> (2u * j)) & 3u) - 1) * d);
    }
''' + B_COMMIT)

# IQ1_M: 56-byte super-blocks (word aligned): qs[32], qh[16], scales[4 x uint16] with the fp16 super-scale in the scale words' top nibbles.
IQ1_M = dict(
    name='iq1_m', fmt='IQ1_M', kreq='256',
    extra='layout(set = 0, binding = 4, std430) readonly  buffer BufGrid { uint iq1sGrid[]; };   // 2048 entries x 8 int8 ternary lanes (2 uints each)\n',
    layout='Bank layout: [E, M, K/256 super-blocks of 56 bytes]: qs[32], qh[16], scales[4 x uint16] (fp16 super-scale = top nibbles of the four words). Sub-block ib = 4 groups of 8: group l\n// grid index = qs[4ib+l] | ((l even ? qh<<8 : qh<<4) & 0x700) with qh = qh[2ib + l/2], delta sign = qh bit 3 (l even) / 7 (l odd), dl = d * (2s+1), s = (sc[ib/2] >> (6(ib%2) + 3(l/2))) & 7;\n// value = dl * (grid int8 + delta). This thread owns groups 2*half_ and 2*half_+1 (16 elements), which share one qh byte and one dl.',
    body='''const uint IQ1_M_BLOCK_BYTES = 56u;
const float IQ1S_DELTA = 0.125;

struct Stage { uint sw0; uint sw1; uint qs2; uint qhb; uint ib; vec4 bv; };   // sw0/sw1: the 4 scale words; qs2: this half's 2 qs bytes; qhb: its qh byte; ib: sub-block

''' + LOAD_SIG + '''    st.sw0 = 0u; st.sw1 = 0u; st.qs2 = 0u; st.qhb = 0u; st.ib = 0u;
    if (rowValid) {
        uint s = sb * 2u + blk;
        uint base = rowBase + (s >> 3u) * IQ1_M_BLOCK_BYTES;
        uint ib = s & 7u;
        st.ib = ib;
        st.sw0 = weight[(base + 48u) >> 2u];
        st.sw1 = weight[((base + 48u) >> 2u) + 1u];
        uint q = base + ib * 4u + half_ * 2u;
        st.qs2 = readByte(q) | (readByte(q + 1u) << 8u);
        st.qhb = readByte(base + 32u + ib * 2u + half_);
    }
''' + B_LOAD + '\n' + COMMIT_SIG + ZERO_A + '''        uint sc0 = st.sw0 & 0xFFFFu, sc1 = st.sw0 >> 16u, sc2 = st.sw1 & 0xFFFFu, sc3 = st.sw1 >> 16u;
        uint dBits = (sc0 >> 12u) | ((sc1 >> 8u) & 0x00F0u) | ((sc2 >> 4u) & 0x0F00u) | (sc3 & 0xF000u);
        float d = unpackHalf2x16(dBits).x;
        uint ib = st.ib;
        uint scWord = ((ib >> 1u) == 0u) ? sc0 : ((ib >> 1u) == 1u) ? sc1 : ((ib >> 1u) == 2u) ? sc2 : sc3;
        uint sub = (scWord >> (6u * (ib & 1u) + 3u * half_)) & 7u;
        float dl = d * float(2u * sub + 1u);
        for (uint pl = 0u; pl < 2u; pl++) {
            uint idx = ((st.qs2 >> (8u * pl)) & 0xFFu) | (((pl == 0u) ? (st.qhb << 8u) : (st.qhb << 4u)) & 0x700u);
            float delta = (((pl == 0u) ? (st.qhb & 0x08u) : (st.qhb & 0x80u)) != 0u) ? -IQ1S_DELTA : IQ1S_DELTA;
            uint ga = iq1sGrid[2u * idx];
            uint gb = iq1sGrid[2u * idx + 1u];
            for (uint e = 0u; e < 4u; e++) {
                sharedA[aBase + pl * 8u + e]      = float16_t(dl * (float(bitfieldExtract(int(ga), int(8u * e), 8)) + delta));
                sharedA[aBase + pl * 8u + 4u + e] = float16_t(dl * (float(bitfieldExtract(int(gb), int(8u * e), 8)) + delta));
            }
        }
    }
''' + B_COMMIT)

SHADERS = [IQ4_NL, IQ4_XS, IQ3_S, IQ2_XXS, IQ2_XS, IQ2_S, IQ3_XXS, Q2_0, IQ1_M]


def render(spec):
    h = HEADER
    h = h.replace('__FMT__', spec['fmt']).replace('__LOWER__', spec['name']).replace('__LAYOUT__', spec['layout'])
    h = h.replace('__KREQ__', spec['kreq']).replace('__EXTRA_BINDINGS__', spec['extra'])
    return h + '\n' + spec['body'] + MAIN


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    out = os.path.join(here, 'shaders')
    for spec in SHADERS:
        path = os.path.join(out, f"moe_grouped_matmul_{spec['name']}_coopmat_m64.comp")
        with open(path, 'w', encoding='utf-8', newline='\n') as f:
            f.write(render(spec))
        print('wrote', path)


if __name__ == '__main__':
    main()
