import re

for q in ['q4_k', 'q5_k', 'q6_k']:
    path = f'native/vulkan/shaders/moe_grouped_matmul_{q}_coopmat_m64.comp'
    s = open(path, newline='', encoding='utf-8').read().replace('\r\n', '\n')

    def rep(a, b, cnt=1):
        global s
        assert s.count(a) == cnt, (q, s.count(a), a[:80])
        s = s.replace(a, b)

    s = s.replace('#version 450\n', '#version 450\n// ROW-PAIR VARIANT (issue #691), GENERATED by native/vulkan/gen_moe_rowpair.py from the _m64 shader: one workgroup covers up to 32 token\n// rows of an expert (two 16-row tiles) and dequantises each super-block of weights ONCE for both. The tile list must be built with 32-row tiles.\n', 1)
    rep('shared float16_t sharedB[TN * STRIDE];', 'shared float16_t sharedB[TN * STRIDE];\nshared float16_t sharedB2[TN * STRIDE];')
    rep('vec4 bv[4]; }', 'vec4 bv[4]; vec4 bv2[4]; }')
    rep('uint expertRows, inout Stage st) {', 'uint expertRows, bool has2, inout Stage st) {')
    rep('''        st.bv[j] = (localRowBase + bRow) < expertRows ? x4[xRowBase4 + bRow * (pc.K / 4u) + sb * (SB / 4u) + c4] : vec4(0.0);
''', '''        st.bv[j] = (localRowBase + bRow) < expertRows ? x4[xRowBase4 + bRow * (pc.K / 4u) + sb * (SB / 4u) + c4] : vec4(0.0);
        if (has2)
            st.bv2[j] = (localRowBase + TN + bRow) < expertRows ? x4[xRowBase4 + (TN + bRow) * (pc.K / 4u) + sb * (SB / 4u) + c4] : vec4(0.0);
''')
    rep('uint lane, bool rowValid) {\n', 'uint lane, bool rowValid, bool has2) {\n')
    rep('''        sharedB[o + 3u] = float16_t(st.bv[j].w);
''', '''        sharedB[o + 3u] = float16_t(st.bv[j].w);
        if (has2) {
            sharedB2[o]      = float16_t(st.bv2[j].x);
            sharedB2[o + 1u] = float16_t(st.bv2[j].y);
            sharedB2[o + 2u] = float16_t(st.bv2[j].z);
            sharedB2[o + 3u] = float16_t(st.bv2[j].w);
        }
''')
    rep('''    coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator> sums =
        coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator>(0.0);
''', '''    coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator> sums =
        coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator>(0.0);
    coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator> sums2 =
        coopmat<float, gl_ScopeSubgroup, TM, TN, gl_MatrixUseAccumulator>(0.0);
    bool has2 = (expertRows - localRowBase) > TN;   // workgroup-uniform
''')
    s, n1 = re.subn(r'expertRows, st\);', 'expertRows, has2, st);', s)
    assert n1 == 2, (q, n1)
    rep('commitStage(st, tid, sg, mLocal, lane, rowValid);', 'commitStage(st, tid, sg, mLocal, lane, rowValid, has2);')
    rep('''            sums = coopMatMulAdd(aTile, bTile, sums);
        }''', '''            sums = coopMatMulAdd(aTile, bTile, sums);
            if (has2) {
                coopmat<float16_t, gl_ScopeSubgroup, TK, TN, gl_MatrixUseB> bTile2;
                coopMatLoad(bTile2, sharedB2, kSlice, STRIDE, gl_CooperativeMatrixLayoutColumnMajor);
                sums2 = coopMatMulAdd(aTile, bTile2, sums2);
            }
        }''')
    a = s.index('    coopMatStore(sums, storeStage')
    b = s.rindex('}')
    epi = '''    for (uint hh = 0u; hh < 2u; hh++) {
        if (hh == 1u && !has2) break;
        if (hh == 0u) coopMatStore(sums, storeStage, sg * TM * TN, TM, gl_CooperativeMatrixLayoutColumnMajor);
        else          coopMatStore(sums2, storeStage, sg * TM * TN, TM, gl_CooperativeMatrixLayoutColumnMajor);
        barrier();

        for (uint i = 0u; i < 4u; i++) {
            uint idx = lane64 + i * WAVE;
            if (idx >= TM * TN) break;
            uint localRowInTile = idx / TM;
            uint m = idx - localRowInTile * TM;
            uint lr = localRowBase + hh * TN + localRowInTile;
            uint mG = mBase + sg * TM + m;
            if (lr < expertRows && mG < pc.M) {
                uint packedRow = expertStart + lr;
                y[packedRow * pc.M + mG] = storeStage[sg * TM * TN + localRowInTile * TM + m];
            }
        }
        barrier();
    }
'''
    s = s[:a] + epi + s[b:]
    out = f'native/vulkan/shaders/moe_grouped_matmul_{q}_coopmat_m64r2.comp'
    open(out, 'w', newline='', encoding='utf-8').write(s.replace('\n', '\r\n'))
    print('wrote', out)
