#!/usr/bin/env python3
"""Generates the split-K twins of the blocked 128x128x4 coopmat GEMM shaders.

For grids with fewer tiles than compute units (small m at n = 128: ffn-down and the attention/GDN output projections launch
20-32 workgroups on a 40-CU part), gl_WorkGroupID.z selects a K slice and a private C slab; splitk_reduce_f32.comp sums the
slabs. The twin differs from its base shader only by one extra push constant (chunksPerSplit) and two defines, so the quant
-specific A-staging code is reused verbatim. Re-run after editing a base shader:

    python native/vulkan/gen_splitk_variants.py
"""
import pathlib, re, sys

SHADERS = pathlib.Path(__file__).parent / "shaders"
QUANTS = ["q4_k", "q5_k", "q6_k", "q8_0"]

for q in QUANTS:
    base = SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4.comp"
    text = base.read_bytes().decode("utf-8", errors="surrogateescape")
    out = text

    assert out.count("    uint rowUints;") == 1, f"{base.name}: expected exactly one rowUints push constant"
    out = out.replace("    uint rowUints;", "    uint rowUints;\n    uint chunksPerSplit;  // BK=32 chunks owned by each z-slice (split-K)", 1)

    m = re.search(r"^#define GEMM_CHUNKS .*$", out, re.M)
    assert m, f"{base.name}: no GEMM_CHUNKS define"
    out = out[:m.end()] + "\n#define GEMM_SPLITK\n#define GEMM_CHUNKS_PER_SPLIT pc.chunksPerSplit" + out[m.end():]

    banner = ("// SPLIT-K TWIN of " + base.name + " -- GENERATED by native/vulkan/gen_splitk_variants.py, do not edit.\n"
              "// gl_WorkGroupID.z selects a K slice and a private C slab; splitk_reduce_f32.comp sums the slabs.\n")
    nl = out.index("\n") + 1   # keep '#version' first
    out = out[:nl] + banner + out[nl:]

    dst = SHADERS / f"matmul_{q}_gemm_coopmat_128x128x4_splitk.comp"
    dst.write_bytes(out.encode("utf-8", errors="surrogateescape"))
    print("wrote", dst.name)
