"""Canonical tool-use renderer for task-LoRA training.

Extracts structured tool definitions from a glaive_func_calling dataset row and
renders the prompt via ``tokenizer.apply_chat_template(..., tools=tools)`` so that
the ``<tools>`` block is **template-generated** — bit-identical to what dotLLM
produces at serve time (parity verified in FORMAT.md §3).

Schema (confirmed from NousResearch/hermes-function-calling-v1 / glaive_func_calling):
  - ``row['tools']``  — JSON *string*, already a list of
                         ``{"type":"function","function":{...}}`` objects ready for HF.
  - ``row['conversations']`` — ShareGPT list; turns have ``'from'`` and ``'value'`` keys.
  - Multi-turn rows: several ``gpt`` turns; only those starting with ``<tool_call>``
                     are tool calls.

Training strategy: for each row we supervise the **first** ``gpt`` turn that begins
with ``<tool_call>``.  The prompt is everything up to (but not including) that turn,
rendered with ``apply_chat_template(tools=..., add_generation_prompt=True)``.
"""
from __future__ import annotations
import json
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from masking import build_labels

_SHAREGPT_ROLE = {
    "system": "system",
    "human": "user",
    "user": "user",
    "gpt": "assistant",
    "assistant": "assistant",
    "tool": "tool",
}


def extract_tools(row: dict) -> list[dict]:
    """Return the HF tool-object list from a glaive_func_calling row.

    The dataset stores tools as a JSON string in ``row['tools']``.  Each entry is
    already ``{"type":"function","function":{...}}``, so we just parse and return.

    Parameters
    ----------
    row:
        A single dataset row (dict).

    Returns
    -------
    list[dict]
        List of ``{"type":"function","function":{...}}`` objects.

    Raises
    ------
    ValueError
        If the ``tools`` field is absent or empty.
    """
    raw = row.get("tools")
    if not raw:
        raise ValueError("Row has no 'tools' field — cannot extract tool definitions.")
    tools = json.loads(raw) if isinstance(raw, str) else raw
    if not tools:
        raise ValueError("'tools' field is empty.")
    return tools


def render_tooluse(tok, row: dict) -> tuple[list[int], list[int]]:
    """Render a tool-use training example using the tokenizer chat template.

    Builds the prompt from the system + user (+ any prior tool-exchange) turns,
    renders it with ``apply_chat_template(tools=..., add_generation_prompt=True)``
    so the ``<tools>`` block is template-generated (matching dotLLM serving), then
    tokenises and masks so only the assistant ``<tool_call>`` completion is supervised.

    For multi-turn rows the **first** ``gpt`` turn that starts with ``<tool_call>``
    is chosen as the supervised completion.  All earlier turns (including any leading
    ``tool`` / ``gpt`` exchanges) form the prompt.

    Parameters
    ----------
    tok:
        A Hugging Face ``PreTrainedTokenizer`` / ``PreTrainedTokenizerFast``.
    row:
        A single glaive_func_calling dataset row (dict).

    Returns
    -------
    tuple[list[int], list[int]]
        ``(input_ids, labels)`` where prompt positions in ``labels`` are ``-100``.

    Raises
    ------
    ValueError
        If no ``gpt`` turn with a ``<tool_call>`` is found in the conversation.
    """
    tools = extract_tools(row)
    conversations = row["conversations"]

    # Find the index of the first gpt turn that is a <tool_call> completion.
    target_idx: int | None = None
    for i, turn in enumerate(conversations):
        if turn["from"] == "gpt":
            content = turn.get("value", turn.get("content", ""))
            if content.lstrip().startswith("<tool_call>"):
                target_idx = i
                break

    if target_idx is None:
        raise ValueError(
            "No gpt turn with <tool_call> found in conversation — cannot render tool-use example."
        )

    # Build prompt messages from all turns before the target, skipping the system
    # turn's boilerplate (the <tools> block is re-generated by the template).
    # We replace the system turn's content with a clean version that strips the
    # embedded <tools>...</tools> boilerplate so it isn't duplicated.
    prompt_msgs: list[dict] = []
    for turn in conversations[:target_idx]:
        role = _SHAREGPT_ROLE.get(turn["from"], turn["from"])
        content = turn.get("value", turn.get("content", ""))
        if role == "system":
            # Strip embedded <tools>...</tools> block from the dataset's system text
            content = _strip_tools_block(content)
        prompt_msgs.append({"role": role, "content": content})

    # Completion: the full gpt <tool_call> turn content
    completion = conversations[target_idx].get("value",
                 conversations[target_idx].get("content", ""))

    # Render prompt via template with structured tools= — this produces the
    # template-generated <tools> block (matching dotLLM serving).
    prompt_text: str = tok.apply_chat_template(
        prompt_msgs,
        tools=tools,
        add_generation_prompt=True,
        tokenize=False,
    )

    p_ids: list[int] = tok(prompt_text, add_special_tokens=False)["input_ids"]
    c_ids: list[int] = tok(completion, add_special_tokens=False)["input_ids"]
    if tok.eos_token_id is not None:
        c_ids = c_ids + [tok.eos_token_id]

    return build_labels(p_ids, c_ids)


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _strip_tools_block(system_text: str) -> str:
    """Remove the embedded ``<tools>...</tools>`` block (and surrounding boilerplate)
    from a glaive_func_calling system message.

    The dataset injects the tool list inline; since we pass tools= to the template
    we must remove it to avoid duplication.  We strip:
    1. The literal ``<tools>\\n...\\n</tools>`` block.
    2. Any leading sentence fragment that introduced the block (the dataset's
       standard preamble ends with ``<tools>`` so this is typically the same line).
    After stripping, a bare preamble like
       "You are a function calling AI model. You are provided with function
       signatures within <tools></tools> XML tags."
    is collapsed to a plain
       "You are a helpful assistant."
    when nothing meaningful remains — but if the author added a non-boilerplate
    prefix we preserve that instead.
    """
    import re

    # Remove the <tools>...</tools> block (including tags and surrounding newlines)
    stripped = re.sub(r"<tools>\s*.*?\s*</tools>", "", system_text, flags=re.DOTALL)

    # Remove the standard glaive boilerplate sentence that references <tools> tags
    stripped = re.sub(
        r"You are provided with function signatures within <tools></tools> XML tags\.?\s*",
        "",
        stripped,
    )
    # Remove inline tool-call format instructions that are re-generated by the template
    stripped = re.sub(
        r"Use the following pydantic model json schema.*?</tool_call>",
        "",
        stripped,
        flags=re.DOTALL,
    )
    stripped = re.sub(
        r"For each function call return a json object.*?</tool_call>",
        "",
        stripped,
        flags=re.DOTALL,
    )
    stripped = stripped.strip()
    if not stripped:
        stripped = "You are a helpful assistant."
    return stripped
