using System.Runtime.InteropServices;
using DotLLM.Core.Configuration;
using DotLLM.Cpu.Kernels;
using DotLLM.Vulkan;
using DotLLM.Vulkan.Kernels;
using Xunit;

namespace DotLLM.Tests.Unit.Vulkan;

/// <summary>
/// Issue #823: grouped-by-expert coopmat GEMMs for the packed IQ3_S / IQ4_XS / IQ4_NL expert banks (generated by
/// <c>native/vulkan/gen_moe_grouped_iq.py</c>). Each case runs the grouped kernel on the legacy grid AND the indirect tile list over RANDOM
/// block bytes (every byte of a block feeds the result, so a mis-read qh / sign / scale / nibble plane is O(1) wrong) and compares against the
/// production CPU dequant (<see cref="Dequantize.ToFloat32"/>) dotted in double. The kernels differ from it only in F16 operand precision, so
/// the envelope is a small multiple of 2^-11 of the accumulated magnitude. Shapes are discriminating: experts with 0, 1, 15, 16, 17, 33 and 64
/// rows, m not a multiple of the 64-row tile, K both a single staging round and the real file's width.
/// </summary>
[Trait("Category", "GPU")]
[Collection("VulkanKernels")]
public sealed class VulkanMoeGroupedIqCoopmatTests
{
    private static byte[] RandomBank(Random rng, long rows, int rowBytes, int blockBytes)
    {
        var bytes = new byte[rows * rowBytes];
        rng.NextBytes(bytes);
        for (long off = 0; off + blockBytes <= bytes.Length; off += blockBytes)
        {
            IqBlockScale.Set(bytes, off, blockBytes, (Half)(0.002f + (float)rng.NextDouble() * 0.02f));
        }
        return bytes;
    }

    [SkippableTheory]
    [InlineData(QuantizationType.IQ3_S, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ3_S, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]    // real gate/up K = hidden 2560 (10 super-blocks), m not a multiple of 64
    [InlineData(QuantizationType.IQ4_XS, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ4_XS, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ4_NL, 64, 64, "16,15,17,1")]                          // single staging round
    [InlineData(QuantizationType.IQ4_NL, 100, 640, "5,0,1,40,17,0,3")]                   // real down K = 640 (not a multiple of 256)
    [InlineData(QuantizationType.IQ4_NL, 130, 704, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ2_XXS, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ2_XXS, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ2_XS, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ2_XS, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ2_S, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ2_S, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ3_XXS, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ3_XXS, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.IQ1_M, 100, 512, "5,0,1,40,17,0,3")]
    [InlineData(QuantizationType.IQ1_M, 130, 2560, "0,3,0,17,40,16,15,1,33,64,2,0")]
    [InlineData(QuantizationType.Q2_0, 64, 64, "16,15,17,1")]                           // single block / staging round
    [InlineData(QuantizationType.Q2_0, 100, 640, "5,0,1,40,17,0,3")]                    // ISTA down K = 640
    [InlineData(QuantizationType.Q2_0, 130, 704, "0,3,0,17,40,16,15,1,33,64,2,0")]
    public void Grouped_MatchesCpuDequantOracle(QuantizationType qt, int m, int k, string countsCsv)
    {
        VulkanMatMulF32KernelTests.SkipIfUnavailable(out string spvDir);
        using var device = VulkanDevice.Create();
        var iq = MoeIndexedMatmulIqMmvqKernel.FromQuantizationType(qt)!.Value;
        Skip.IfNot(MoeGroupedMatmulIqCoopmatKernel.IsSupportedOn(device, spvDir, iq) && MoeBuildTileListKernel.IsSupportedOn(spvDir),
            "coopmat / native wave64 / SPIR-V unavailable.");

        int[] counts = Array.ConvertAll(countsCsv.Split(','), int.Parse);
        int E = counts.Length, rows = counts.Sum();
        uint[] offsets = new uint[E + 1];
        int[] expertOfRow = new int[rows];
        for (int e = 0, r = 0; e < E; e++)
        {
            offsets[e + 1] = offsets[e] + (uint)counts[e];
            for (int i = 0; i < counts[e]; i++) expertOfRow[r++] = e;
        }

        var (blockBytes, group) = MoeIndexedMatmulIqMmvqKernel.Describe(iq);
        int rowBytes = (k / group) * blockBytes;
        var rng = new Random(0x823 + (int)qt * 101 + m * 31 + k + rows);
        byte[] bank = RandomBank(rng, (long)E * m, rowBytes, blockBytes);
        float[] x = new float[(long)rows * k];
        for (int i = 0; i < x.Length; i++) x[i] = (float)(rng.NextDouble() * 2 - 1);

        using var codebooks = Iq3Codebooks.Create(device);
        using var codebooks2 = Iq2Codebooks.Create(device);
        using var codebooks1 = Iq1Codebooks.Create(device);
        using var bufW = device.Allocate((bank.Length + 3L) & ~3L);
        using var bufX = device.Allocate((long)rows * k * sizeof(float));
        using var bufOff = device.Allocate(MoeBuildTileListKernel.OffsetsBufferUints(E, rows) * sizeof(uint));
        using var bufArgs = device.Allocate(2 * MoeBuildTileListKernel.ArgsStrideBytes);
        using var yLegacy = device.Allocate((long)rows * m * sizeof(float));
        using var yIndirect = device.Allocate((long)rows * m * sizeof(float));
        device.Upload(bank, bufW);
        device.Upload(x, bufX);
        device.Upload(MemoryMarshal.AsBytes<uint>(offsets), bufOff);

        using var kernel = MoeGroupedMatmulIqCoopmatKernel.Create(device, spvDir, iq, codebooks, codebooks2, codebooks1);
        using var build = MoeBuildTileListKernel.Create(device, spvDir);
        kernel.Launch(bufW, bufX, bufOff, yLegacy, m, k, rows, E, maxRowsPerExpert: counts.Max());
        using (var ctx = device.CreateSubmitContext())
        {
            ctx.Begin();
            build.Record(ctx.CommandBuffer, bufOff, bufArgs, E, kernel.MTiles(m), kernel.MTiles(m), kernel.RowTile);
            KernelSupport.ComputeToIndirectAndComputeBarrier(ctx.CommandBuffer);
            kernel.RecordIndirect(ctx.CommandBuffer, bufW, bufX, bufOff, yIndirect, bufArgs, 0, m, k, rows, E);
            ctx.SubmitAndWait();
        }

        float[] a = new float[(long)rows * m], b = new float[(long)rows * m];
        device.Download(yLegacy, a);
        device.Download(yIndirect, b);

        float[] r0 = CpuOracle(bank, qt, expertOfRow, x, m, k, rows, rowBytes);
        float maxAbs = r0.Max(MathF.Abs);
        Assert.True(maxAbs > 1e-3f, "reference output is degenerate (all ~0): the comparison would be vacuous.");
        float tol = 6e-3f * maxAbs;
        float worst = 0;
        for (int i = 0; i < r0.Length; i++)
        {
            Assert.True(a[i] == b[i], $"{qt} idx {i} (row {i / m}, col {i % m}): legacy grid {a[i]:G9} != indirect {b[i]:G9}");
            float d = MathF.Abs(a[i] - r0[i]);
            worst = MathF.Max(worst, d);
            Assert.True(d <= tol, $"{qt} idx {i} (row {i / m}, col {i % m}, expert {expertOfRow[i / m]}): grouped {a[i]:G9} vs cpu {r0[i]:G9} (tol {tol:G4}, maxAbs {maxAbs:G4})");
        }
        Assert.True(worst > 0 || r0.Length == 0, "bit-identical to the F32 CPU oracle is implausible with F16 operands; the grouped kernel may not have run.");
    }

    private static unsafe float[] CpuOracle(byte[] bank, QuantizationType qt, int[] expertOfRow, float[] x, int m, int k, int rows, int rowBytes)
    {
        var y = new float[(long)rows * m];
        var w = new float[k];
        fixed (byte* bankPtr = bank)
        {
            // Dequantize each (expert, m) weight row once, then dot it with every packed row of that expert.
            int E = expertOfRow.Max() + 1;
            var firstRow = new int[E + 1];
            Array.Fill(firstRow, -1);
            for (int r = 0; r < rows; r++) if (firstRow[expertOfRow[r]] < 0) firstRow[expertOfRow[r]] = r;
            for (int e = 0; e < E; e++)
            {
                if (firstRow[e] < 0) continue;
                for (int mm = 0; mm < m; mm++)
                {
                    Dequantize.ToFloat32((nint)(bankPtr + ((long)e * m + mm) * rowBytes), k, qt, w);
                    for (int r = firstRow[e]; r < rows && expertOfRow[r] == e; r++)
                    {
                        double acc = 0;
                        long xo = (long)r * k;
                        for (int i = 0; i < k; i++) acc += (double)w[i] * x[xo + i];
                        y[(long)r * m + mm] = (float)acc;
                    }
                }
            }
        }
        return y;
    }
}
